// priority: 0

ServerEvents.tags('item', event => {
	event.get('raspberry_flavoured:logs')
		.add('minecraft:oak_log')
		.add('minecraft:spruce_log')
		.add('minecraft:birch_log')
		.add('minecraft:jungle_log')
		.add('minecraft:acacia_log')
		.add('minecraft:dark_oak_log')
		.add('minecraft:mangrove_log')
		.add('minecraft:crimson_stem')
		.add('minecraft:warped_stem')
		.add('architects_palette:twisted_log')
		.add('ecologics:coconut_log')
		.add('ecologics:azalea_log')
		.add('atmospheric:rosewood_log')
		.add('atmospheric:morado_log')
		.add('atmospheric:yucca_log')
		.add('atmospheric:watchful_aspen_log')
		.add('autumnity:maple_log')
		.add('environmental:willow_log')
		.add('environmental:cherry_log')
		.add('environmental:wisteria_log')
		.add('upgrade_aquatic:driftwood_log')
		.add('upgrade_aquatic:river_log')
		.add('windswept:chestnut_log')
		.add('culturaldelights:avocado_log')
		
	event.get('raspberry_flavoured:wood')
		.add('minecraft:oak_wood')
		.add('minecraft:spruce_wood')
		.add('minecraft:birch_wood')
		.add('minecraft:jungle_wood')
		.add('minecraft:acacia_wood')
		.add('minecraft:dark_oak_wood')
		.add('minecraft:mangrove_wood')
		.add('minecraft:crimson_hyphae')
		.add('minecraft:warped_hyphae')
		.add('architects_palette:twisted_wood')
		.add('ecologics:coconut_wood')
		.add('ecologics:azalea_wood')
		.add('atmospheric:rosewood')
		.add('atmospheric:morado_wood')
		.add('atmospheric:yucca_wood')
		.add('autumnity:maple_wood')
		.add('environmental:willow_wood')
		.add('environmental:cherry_wood')
		.add('environmental:wisteria_wood')
		.add('upgrade_aquatic:driftwood')
		.add('upgrade_aquatic:river_wood')
		.add('windswept:chestnut_wood')
		.add('culturaldelights:avocado_wood')
		
	event.get('raspberry_flavoured:stripped_logs')
		.add('minecraft:stripped_oak_log')
		.add('minecraft:stripped_spruce_log')
		.add('minecraft:stripped_birch_log')
		.add('minecraft:stripped_jungle_log')
		.add('minecraft:stripped_acacia_log')
		.add('minecraft:stripped_dark_oak_log')
		.add('minecraft:stripped_mangrove_log')
		.add('minecraft:stripped_crimson_stem')
		.add('minecraft:stripped_warped_stem')
		.add('architects_palette:stripped_twisted_log')
		.add('ecologics:stripped_coconut_log')
		.add('ecologics:stripped_azalea_log')
		.add('atmospheric:stripped_rosewood_log')
		.add('atmospheric:stripped_morado_log')
		.add('atmospheric:stripped_yucca_log')
		.add('kubejs:latex_jungle_log')
		.add('kubejs:latex_rosewood_log')
		.add('autumnity:stripped_maple_log')
		.add('autumnity:sappy_maple_log')
		.add('environmental:stripped_willow_log')
		.add('environmental:stripped_cherry_log')
		.add('environmental:stripped_wisteria_log')
		.add('upgrade_aquatic:stripped_driftwood_log')
		.add('upgrade_aquatic:stripped_river_log')
		.add('windswept:stripped_chestnut_log')
		
	event.get('raspberry_flavoured:stripped_wood')
		.add('minecraft:stripped_oak_wood')
		.add('minecraft:stripped_spruce_wood')
		.add('minecraft:stripped_birch_wood')
		.add('minecraft:stripped_jungle_wood')
		.add('minecraft:stripped_acacia_wood')
		.add('minecraft:stripped_dark_oak_wood')
		.add('minecraft:stripped_mangrove_wood')
		.add('minecraft:stripped_crimson_hyphae')
		.add('minecraft:stripped_warped_hyphae')
		.add('architects_palette:stripped_twisted_wood')
		.add('ecologics:stripped_coconut_wood')
		.add('ecologics:stripped_azalea_wood')
		.add('atmospheric:stripped_rosewood')
		.add('atmospheric:stripped_morado_wood')
		.add('atmospheric:stripped_yucca_wood')
		.add('kubejs:latex_jungle_wood')
		.add('kubejs:latex_rosewood')
		.add('autumnity:stripped_maple_wood')
		.add('autumnity:sappy_maple_wood')
		.add('environmental:stripped_willow_wood')
		.add('environmental:stripped_cherry_wood')
		.add('environmental:stripped_wisteria_wood')
		.add('upgrade_aquatic:stripped_driftwood')
		.add('upgrade_aquatic:stripped_river_wood')
		.add('windswept:stripped_chestnut_wood')
		
	event.get('raspberry_flavoured:stone')
		.add('minecraft:cobblestone')
		.add('minecraft:cobblestone_stairs')
		.add('paletteblocks:cobblestone_bricks')
		.add('paletteblocks:cobblestone_brick_stairs')
		.add('paletteblocks:cracked_cobblestone_bricks')
		.add('minecraft:stone')
		.add('minecraft:stone_stairs')
		.add('minecraft:smooth_stone')
		.add('kubejs:smooth_stone_stairs')
		.add('twigs:smooth_stone_bricks')
		.add('twigs:smooth_stone_brick_stairs')
		.add('minecraft:stone_bricks')
		.add('minecraft:stone_brick_stairs')
		.add('minecraft:cracked_stone_bricks')
		.add('minecraft:chiseled_stone_bricks')
		.add('supplementaries:stone_tile')
		.add('supplementaries:stone_tile_stairs')
		.add('architects_palette:heavy_stone_bricks')
		.add('architects_palette:heavy_cracked_stone_bricks')
		.add('twigs:stone_column')
		
	event.get('raspberry_flavoured:stone_half')
		.add('minecraft:cobblestone_slab')
		.add('paletteblocks:cobblestone_brick_slab')
		.add('minecraft:stone_slab')
		.add('minecraft:smooth_stone_slab')
		.add('twigs:smooth_stone_brick_slab')
		.add('minecraft:stone_brick_slab')
		.add('supplementaries:stone_tile_slab')
		.add('minecraft:cobblestone_wall')
		.add('paletteblocks:cobblestone_brick_wall')
		.add('kubejs:smooth_stone_wall')
		.add('twigs:smooth_stone_brick_wall')
		.add('minecraft:stone_brick_wall')
		.add('supplementaries:stone_tile_wall')
		
	event.get('raspberry_flavoured:deepslate')
		.add('minecraft:cobbled_deepslate')
		.add('minecraft:polished_deepslate')
		.add('minecraft:deepslate_bricks')
		.add('minecraft:cracked_deepslate_bricks')
		.add('minecraft:deepslate_tiles')
		.add('minecraft:cracked_deepslate_tiles')
		.add('minecraft:chiseled_deepslate')
		.add('minecraft:cobbled_deepslate_stairs')
		.add('minecraft:polished_deepslate_stairs')
		.add('minecraft:deepslate_brick_stairs')
		.add('minecraft:deepslate_tile_stairs')
		.add('twigs:deepslate_column')
		.add('create:cut_deepslate')
		.add('create:cut_deepslate_stairs')
		.add('create:polished_cut_deepslate')
		.add('create:polished_cut_deepslate_stairs')
		.add('create:cut_deepslate_bricks')
		.add('create:cut_deepslate_brick_stairs')
		.add('create:small_deepslate_bricks')
		.add('create:small_deepslate_brick_stairs')
		.add('create:layered_deepslate')
		.add('create:deepslate_pillar')
		
	event.get('raspberry_flavoured:deepslate_half')
		.add('minecraft:cobbled_deepslate_slab')
		.add('minecraft:polished_deepslate_slab')
		.add('minecraft:deepslate_brick_slab')
		.add('minecraft:deepslate_tile_slab')
		.add('create:cut_deepslate_slab')
		.add('create:polished_cut_deepslate_slab')
		.add('create:cut_deepslate_brick_slab')
		.add('create:small_deepslate_brick_slab')
		.add('minecraft:cobbled_deepslate_wall')
		.add('minecraft:polished_deepslate_wall')
		.add('minecraft:deepslate_brick_wall')
		.add('minecraft:deepslate_tile_wall')
		.add('create:cut_deepslate_wall')
		.add('create:polished_cut_deepslate_wall')
		.add('create:cut_deepslate_brick_wall')
		.add('create:small_deepslate_brick_wall')
		
	event.get('raspberry_flavoured:granite')
		.add('minecraft:granite')
		.add('minecraft:granite_stairs')
		.add('minecraft:polished_granite')
		.add('minecraft:polished_granite_stairs')
		.add('quark:granite_bricks')
		.add('quark:granite_bricks_stairs')
		.add('quark:chiseled_granite_bricks')
		.add('quark:granite_pillar')
		.add('create:cut_granite')
		.add('create:cut_granite_stairs')
		.add('create:polished_cut_granite')
		.add('create:polished_cut_granite_stairs')
		.add('create:cut_granite_bricks')
		.add('create:cut_granite_brick_stairs')
		.add('create:small_granite_bricks')
		.add('create:small_granite_brick_stairs')
		.add('create:layered_granite')
		.add('create:granite_pillar')
		
	event.get('raspberry_flavoured:granite_half')
		.add('minecraft:granite_slab')
		.add('minecraft:polished_granite_slab')
		.add('quark:granite_bricks_slab')
		.add('create:cut_granite_slab')
		.add('create:polished_cut_granite_slab')
		.add('create:cut_granite_brick_slab')
		.add('create:small_granite_brick_slab')
		.add('minecraft:granite_wall')
		.add('quark:granite_bricks_wall')
		.add('paletteblocks:polished_granite_wall')
		.add('create:cut_granite_wall')
		.add('create:polished_cut_granite_wall')
		.add('create:cut_granite_brick_wall')
		.add('create:small_granite_brick_wall')
		
	event.get('raspberry_flavoured:diorite')
		.add('minecraft:diorite')
		.add('minecraft:diorite_stairs')
		.add('minecraft:polished_diorite')
		.add('minecraft:polished_diorite_stairs')
		.add('quark:diorite_bricks')
		.add('quark:diorite_bricks_stairs')
		.add('quark:chiseled_diorite_bricks')
		.add('quark:diorite_pillar')
		.add('create:cut_diorite')
		.add('create:cut_diorite_stairs')
		.add('create:polished_cut_diorite')
		.add('create:polished_cut_diorite_stairs')
		.add('create:cut_diorite_bricks')
		.add('create:cut_diorite_brick_stairs')
		.add('create:small_diorite_bricks')
		.add('create:small_diorite_brick_stairs')
		.add('create:layered_diorite')
		.add('create:diorite_pillar')
		
	event.get('raspberry_flavoured:diorite_half')
		.add('minecraft:diorite_slab')
		.add('minecraft:polished_diorite_slab')
		.add('quark:diorite_bricks_slab')
		.add('create:cut_diorite_slab')
		.add('create:polished_cut_diorite_slab')
		.add('create:cut_diorite_brick_slab')
		.add('create:small_diorite_brick_slab')
		.add('minecraft:diorite_wall')
		.add('quark:diorite_bricks_wall')
		.add('paletteblocks:polished_diorite_wall')
		.add('create:cut_diorite_wall')
		.add('create:polished_cut_diorite_wall')
		.add('create:cut_diorite_brick_wall')
		.add('create:small_diorite_brick_wall')
		
	event.get('raspberry_flavoured:andesite')
		.add('minecraft:andesite')
		.add('minecraft:andesite_stairs')
		.add('minecraft:polished_andesite')
		.add('minecraft:polished_andesite_stairs')
		.add('quark:andesite_bricks')
		.add('quark:andesite_bricks_stairs')
		.add('quark:chiseled_andesite_bricks')
		.add('quark:andesite_pillar')
		.add('create:cut_andesite')
		.add('create:cut_andesite_stairs')
		.add('create:polished_cut_andesite')
		.add('create:polished_cut_andesite_stairs')
		.add('create:cut_andesite_bricks')
		.add('create:cut_andesite_brick_stairs')
		.add('create:small_andesite_bricks')
		.add('create:small_andesite_brick_stairs')
		.add('create:layered_andesite')
		.add('create:andesite_pillar')
		
	event.get('raspberry_flavoured:andesite_half')
		.add('minecraft:andesite_slab')
		.add('minecraft:polished_andesite_slab')
		.add('quark:andesite_bricks_slab')
		.add('create:cut_andesite_slab')
		.add('create:polished_cut_andesite_slab')
		.add('create:cut_andesite_brick_slab')
		.add('create:small_andesite_brick_slab')
		.add('minecraft:andesite_wall')
		.add('quark:andesite_bricks_wall')
		.add('paletteblocks:polished_andesite_wall')
		.add('create:cut_andesite_wall')
		.add('create:polished_cut_andesite_wall')
		.add('create:cut_andesite_brick_wall')
		.add('create:small_andesite_brick_wall')
		
	event.get('raspberry_flavoured:calcite')
		.add('minecraft:calcite')
		.add('quark:calcite_stairs')
		.add('quark:polished_calcite')
		.add('quark:polished_calcite_stairs')
		.add('quark:calcite_bricks')
		.add('quark:calcite_bricks_stairs')
		.add('quark:chiseled_calcite_bricks')
		.add('quark:calcite_pillar')
		.add('architects_palette:calcite_bricks')
		.add('architects_palette:calcite_brick_stairs')
		.add('architects_palette:calcite_pillar')
		.add('architects_palette:chiseled_calcite')
		.add('architects_palette:heavy_calcite_bricks')
		.add('create:cut_calcite')
		.add('create:cut_calcite_stairs')
		.add('create:polished_cut_calcite')
		.add('create:polished_cut_calcite_stairs')
		.add('create:cut_calcite_bricks')
		.add('create:cut_calcite_brick_stairs')
		.add('create:small_calcite_bricks')
		.add('create:small_calcite_brick_stairs')
		.add('create:layered_calcite')
		.add('create:calcite_pillar')
		
	event.get('raspberry_flavoured:calcite_half')
		.add('quark:calcite_slab')
		.add('quark:polished_calcite_slab')
		.add('quark:calcite_bricks_slab')
		.add('architects_palette:calcite_brick_slab')
		.add('create:cut_calcite_slab')
		.add('create:polished_cut_calcite_slab')
		.add('create:cut_calcite_brick_slab')
		.add('create:small_calcite_brick_slab')
		.add('quark:calcite_wall')
		.add('quark:calcite_bricks_wall')
		.add('paletteblocks:polished_calcite_wall')
		.add('architects_palette:calcite_brick_wall')
		.add('create:cut_calcite_wall')
		.add('create:polished_cut_calcite_wall')
		.add('create:cut_calcite_brick_wall')
		.add('create:small_calcite_brick_wall')
		
	event.get('raspberry_flavoured:tuff')
		.add('minecraft:tuff')
		.add('quark:tuff_stairs')
		.add('quark:polished_tuff')
		.add('quark:polished_tuff_stairs')
		.add('quark:tuff_bricks')
		.add('quark:tuff_bricks_stairs')
		.add('quark:chiseled_tuff_bricks')
		.add('quark:tuff_pillar')
		.add('architects_palette:tuff_bricks')
		.add('architects_palette:tuff_brick_stairs')
		.add('architects_palette:tuff_pillar')
		.add('architects_palette:chiseled_tuff')
		.add('architects_palette:heavy_tuff_bricks')
		.add('create:cut_tuff')
		.add('create:cut_tuff_stairs')
		.add('create:polished_cut_tuff')
		.add('create:polished_cut_tuff_stairs')
		.add('create:cut_tuff_bricks')
		.add('create:cut_tuff_brick_stairs')
		.add('create:small_tuff_bricks')
		.add('create:small_tuff_brick_stairs')
		.add('create:layered_tuff')
		.add('create:tuff_pillar')
		
	event.get('raspberry_flavoured:tuff_half')
		.add('quark:tuff_slab')
		.add('quark:polished_tuff_slab')
		.add('quark:tuff_bricks_slab')
		.add('architects_palette:tuff_brick_slab')
		.add('create:cut_tuff_slab')
		.add('create:polished_cut_tuff_slab')
		.add('create:cut_tuff_brick_slab')
		.add('create:small_tuff_brick_slab')
		.add('quark:tuff_wall')
		.add('quark:tuff_bricks_wall')
		.add('paletteblocks:polished_tuff_wall')
		.add('architects_palette:tuff_brick_wall')
		.add('create:cut_tuff_wall')
		.add('create:polished_cut_tuff_wall')
		.add('create:cut_tuff_brick_wall')
		.add('create:small_tuff_brick_wall')
		
	event.get('raspberry_flavoured:dripstone')
		.add('minecraft:dripstone_block')
		.add('quark:polished_dripstone')
		.add('quark:dripstone_block_stairs')
		.add('quark:polished_dripstone_stairs')
		.add('quark:dripstone_bricks')
		.add('quark:dripstone_bricks_stairs')
		.add('quark:chiseled_dripstone_bricks')
		.add('quark:dripstone_pillar')
		.add('architects_palette:dripstone_bricks')
		.add('architects_palette:dripstone_brick_stairs')
		.add('architects_palette:dripstone_pillar')
		.add('architects_palette:chiseled_dripstone')
		.add('architects_palette:heavy_dripstone_bricks')
		.add('create:cut_dripstone')
		.add('create:cut_dripstone_stairs')
		.add('create:polished_cut_dripstone')
		.add('create:polished_cut_dripstone_stairs')
		.add('create:cut_dripstone_bricks')
		.add('create:cut_dripstone_brick_stairs')
		.add('create:small_dripstone_bricks')
		.add('create:small_dripstone_brick_stairs')
		.add('create:layered_dripstone')
		.add('create:dripstone_pillar')
		
	event.get('raspberry_flavoured:dripstone_half')
		.add('quark:dripstone_block_slab')
		.add('quark:polished_dripstone_slab')
		.add('quark:dripstone_bricks_slab')
		.add('architects_palette:dripstone_brick_slab')
		.add('create:cut_dripstone_slab')
		.add('create:polished_cut_dripstone_slab')
		.add('create:cut_dripstone_brick_slab')
		.add('create:small_dripstone_brick_slab')
		.add('quark:dripstone_block_wall')
		.add('quark:dripstone_bricks_wall')
		.add('paletteblocks:polished_dripstone_wall')
		.add('architects_palette:dripstone_brick_wall')
		.add('create:cut_dripstone_wall')
		.add('create:polished_cut_dripstone_wall')
		.add('create:cut_dripstone_brick_wall')
		.add('create:small_dripstone_brick_wall')
		
	event.get('raspberry_flavoured:quartz')	
		.add('minecraft:quartz_block')
		.add('minecraft:quartz_stairs')
		.add('minecraft:smooth_quartz')
		.add('minecraft:smooth_quartz_stairs')
		.add('minecraft:chiseled_quartz_block')
		.add('minecraft:quartz_bricks')
		.add('minecraft:quartz_pillar')
		.add('twigs:quartz_column')
		
	event.get('raspberry_flavoured:quartz_half')
		.add('minecraft:quartz_slab')
		.add('minecraft:smooth_quartz_slab')
		
	event.get('raspberry_flavoured:basalt')
		.add('minecraft:smooth_basalt')
		.add('minecraft:basalt')
		.add('paletteblocks:polished_basalt')
		.add('paletteblocks:polished_basalt_stairs')
		.add('minecraft:polished_basalt')
		.add('twigs:polished_basalt_bricks')
		.add('twigs:smooth_basalt_bricks')
		.add('twigs:smooth_basalt_brick_stairs')
		.add('twigs:chiseled_smooth_basalt_bricks')
		.add('architects_palette:basalt_tiles')
		.add('architects_palette:basalt_tile_stairs')
		.add('architects_palette:cracked_basalt_tiles')
		.add('architects_palette:chiseled_basalt_tiles')
		
	event.get('raspberry_flavoured:basalt_half')
		.add('paletteblocks:polished_basalt_slab')
		.add('architects_palette:basalt_tile_slab')
		.add('twigs:smooth_basalt_brick_slab')
		.add('paletteblocks:polished_basalt_wall')
		.add('architects_palette:basalt_tile_wall')
		.add('twigs:smooth_basalt_brick_wall')
		
	event.get('raspberry_flavoured:blackstone')
		.add('kubejs:cobbled_blackstone')
		.add('kubejs:cobbled_blackstone_stairs')
		.add('minecraft:blackstone')
		.add('minecraft:blackstone_stairs')
		.add('minecraft:polished_blackstone')
		.add('minecraft:polished_blackstone_stairs')
		.add('minecraft:chiseled_polished_blackstone')
		.add('minecraft:polished_blackstone_bricks')
		.add('minecraft:polished_blackstone_brick_stairs')
		.add('minecraft:cracked_polished_blackstone_bricks')
		.add('quark:blackstone_bricks')
		.add('quark:blackstone_bricks_stairs')
		.add('supplementaries:blackstone_tile')
		.add('supplementaries:blackstone_tile_stairs')
		.add('twigs:blackstone_column')
		
	event.get('raspberry_flavoured:blackstone_half')
		.add('kubejs:cobbled_blackstone_slab')
		.add('minecraft:blackstone_slab')
		.add('minecraft:polished_blackstone_slab')
		.add('minecraft:polished_blackstone_brick_slab')
		.add('quark:blackstone_bricks_slab')
		.add('supplementaries:blackstone_tile_slab')
		.add('kubejs:cobbled_blackstone_wall')
		.add('minecraft:blackstone_wall')
		.add('minecraft:polished_blackstone_wall')
		.add('minecraft:polished_blackstone_brick_wall')
		.add('quark:blackstone_bricks_wall')
		.add('supplementaries:blackstone_tile_wall')
		
	event.get('raspberry_flavoured:glance')
		.add('oreganized:glance')
		.add('oreganized:glance_stairs')
		.add('oreganized:polished_glance')
		.add('oreganized:polished_glance_stairs')
		.add('oreganized:glance_bricks')
		.add('oreganized:glance_brick_stairs')
		.add('oreganized:chiseled_glance')
		.add('kubejs:glance_pillar')

	event.get('raspberry_flavoured:glance_half')
		.add('oreganized:glance_slab')
		.add('oreganized:polished_glance_slab')
		.add('oreganized:glance_brick_slab')
		.add('oreganized:glance_wall')
		.add('oreganized:glance_brick_wall')
		
	event.get('raspberry_flavoured:sandstone')
		.add('minecraft:sandstone')
		.add('minecraft:sandstone_stairs')
		.add('minecraft:smooth_sandstone')
		.add('minecraft:smooth_sandstone_stairs')
		.add('minecraft:chiseled_sandstone')
		.add('minecraft:cut_sandstone')
		.add('quark:sandstone_bricks')
		.add('quark:sandstone_bricks_stairs')
		
	event.get('raspberry_flavoured:sandstone_half')
		.add('minecraft:sandstone_slab')
		.add('minecraft:cut_sandstone_slab')
		.add('minecraft:smooth_sandstone_slab')
		.add('quark:sandstone_bricks_slab')
		.add('minecraft:sandstone_wall')
		.add('quark:sandstone_bricks_wall')
		
	event.get('raspberry_flavoured:red_sandstone')
		.add('minecraft:red_sandstone')
		.add('minecraft:red_sandstone_stairs')
		.add('minecraft:smooth_red_sandstone')
		.add('minecraft:smooth_red_sandstone_stairs')
		.add('minecraft:chiseled_red_sandstone')
		.add('minecraft:cut_red_sandstone')
		.add('quark:red_sandstone_bricks')
		.add('quark:red_sandstone_bricks_stairs')
		
	event.get('raspberry_flavoured:red_sandstone_half')
		.add('minecraft:red_sandstone_slab')
		.add('minecraft:cut_red_sandstone_slab')
		.add('minecraft:smooth_red_sandstone_slab')
		.add('quark:red_sandstone_bricks_slab')
		.add('minecraft:red_sandstone_wall')
		.add('quark:red_sandstone_bricks_wall')
		
	event.get('raspberry_flavoured:arid_sandstone')
		.add('atmospheric:arid_sandstone')
		.add('atmospheric:arid_sandstone_stairs')
		.add('atmospheric:smooth_arid_sandstone')
		.add('atmospheric:smooth_arid_sandstone_stairs')
		.add('atmospheric:cut_arid_sandstone')
		.add('atmospheric:chiseled_arid_sandstone')
		.add('atmospheric:arid_sandstone_bricks')
		.add('atmospheric:arid_sandstone_brick_stairs')
		
	event.get('raspberry_flavoured:arid_sandstone_half')
		.add('atmospheric:arid_sandstone_slab')
		.add('atmospheric:smooth_arid_sandstone_slab')
		.add('atmospheric:cut_arid_sandstone_slab')
		.add('atmospheric:arid_sandstone_brick_slab')
		.add('atmospheric:arid_sandstone_wall')
		.add('atmospheric:arid_sandstone_brick_wall')
		
	event.get('raspberry_flavoured:red_arid_sandstone')
		.add('atmospheric:red_arid_sandstone')
		.add('atmospheric:red_arid_sandstone_stairs')
		.add('atmospheric:smooth_red_arid_sandstone')
		.add('atmospheric:smooth_red_arid_sandstone_stairs')
		.add('atmospheric:cut_red_arid_sandstone')
		.add('atmospheric:chiseled_red_arid_sandstone')
		.add('atmospheric:red_arid_sandstone_bricks')
		.add('atmospheric:red_arid_sandstone_brick_stairs')
		
	event.get('raspberry_flavoured:red_arid_sandstone_half')
		.add('atmospheric:red_arid_sandstone_slab')
		.add('atmospheric:smooth_red_arid_sandstone_slab')
		.add('atmospheric:cut_red_arid_sandstone_slab')
		.add('atmospheric:red_arid_sandstone_brick_slab')
		.add('atmospheric:red_arid_sandstone_wall')
		.add('atmospheric:red_arid_sandstone_brick_wall')
		
	event.get('raspberry_flavoured:soul_sandstone')
		.add('quark:soul_sandstone')
		.add('quark:soul_sandstone_stairs')
		.add('quark:chiseled_soul_sandstone')
		.add('quark:cut_soul_sandstone')
		.add('quark:smooth_soul_sandstone')
		.add('quark:smooth_soul_sandstone_stairs')
		.add('quark:soul_sandstone_bricks')
		.add('quark:soul_sandstone_bricks_stairs')
		
	event.get('raspberry_flavoured:soul_sandstone_half')
		.add('quark:soul_sandstone_slab')
		.add('quark:cut_soul_sandstone_slab')
		.add('quark:smooth_soul_sandstone_slab')
		.add('quark:soul_sandstone_bricks_slab')
		.add('quark:soul_sandstone_wall')
		.add('quark:soul_sandstone_bricks_wall')
		
	event.get('raspberry_flavoured:gilded_sandstone')
		.add('architects_palette:gilded_sandstone')
		.add('architects_palette:gilded_sandstone_stairs')
		.add('architects_palette:gilded_sandstone_pillar')
		.add('architects_palette:chiseled_gilded_sandstone')
		
	event.get('raspberry_flavoured:gilded_sandstone_half')
		.add('architects_palette:gilded_sandstone_slab')
		
	event.get('raspberry_flavoured:amethyst')
		.add('minecraft:amethyst_block')
		.add('twigs:cut_amethyst')
		.add('sullysmod:polished_jade_block')
		.add('sullysmod:polished_jade_bricks')
		.add('sullysmod:polished_small_jade_bricks')
		.add('sullysmod:polished_jade_shingles')
		.add('sullysmod:polished_jade_tiles')
		.add('sullysmod:polished_chiseled_jade')
		.add('sullysmod:jade_totem')
		.add('sullysmod:polished_jade_pillar')
		.add('sullysmod:polished_jade_brick_stairs')
		.add('sullysmod:polished_small_jade_brick_stairs')
		.add('sullysmod:polished_jade_shingle_stairs')
		.add('sullysmod:polished_jade_tile_stairs')
		.add('caverns_and_chasms:amethyst_block')
		.add('caverns_and_chasms:cut_amethyst')
		.add('caverns_and_chasms:cut_amethyst_bricks')
		.add('caverns_and_chasms:cut_amethyst_brick_stairs')
		
	event.get('raspberry_flavoured:amethyst_half')
		.add('sullysmod:polished_jade_brick_slab')
		.add('sullysmod:polished_small_jade_brick_slab')
		.add('sullysmod:polished_jade_shingle_slab')
		.add('sullysmod:polished_jade_tile_slab')
		.add('caverns_and_chasms:cut_amethyst_brick_slab')
		.add('caverns_and_chasms:cut_amethyst_brick_wall')
		
	event.get('raspberry_flavoured:mossy_stone')
		.add('minecraft:mossy_cobblestone')
		.add('minecraft:mossy_stone_bricks')
		.add('minecraft:mossy_stone_brick_stairs')
		.add('minecraft:mossy_cobblestone_stairs')
		.add('architects_palette:heavy_mossy_stone_bricks')
		.add('paletteblocks:mossy_cobblestone_bricks')
		.add('paletteblocks:mossy_cobblestone_brick_stairs')
		
	event.get('raspberry_flavoured:mossy_stone_half')
		.add('minecraft:mossy_stone_brick_slab')
		.add('minecraft:mossy_cobblestone_slab')
		.add('paletteblocks:mossy_cobblestone_brick_slab')
		.add('minecraft:mossy_cobblestone_wall')
		.add('minecraft:mossy_stone_brick_wall')
		.add('paletteblocks:mossy_cobblestone_brick_wall')
		
	event.get('raspberry_flavoured:purpur')
		.add('minecraft:purpur_block')
		.add('minecraft:purpur_pillar')
		.add('minecraft:purpur_stairs')
		.add('endergetic:cracked_purpur_block')
		
	event.get('raspberry_flavoured:purpur_half')
		.add('minecraft:purpur_slab')
		
	event.get('raspberry_flavoured:midori')
		.add('quark:midori_block')
		.add('quark:midori_pillar')
		.add('quark:midori_block_stairs')
		.add('kubejs:cracked_midori_block')
		
	event.get('raspberry_flavoured:midori_half')
		.add('quark:midori_block_slab')
		
	event.get('raspberry_flavoured:duskbound')
		.add('quark:duskbound_block')
		.add('quark:duskbound_block_stairs')
		
	event.get('raspberry_flavoured:duskbound_half')
		.add('quark:duskbound_block_slab')
		
	event.get('raspberry_flavoured:brick')
		.add('minecraft:bricks')
		.add('minecraft:brick_stairs')
		.add('twigs:mixed_bricks')
		.add('twigs:chiseled_bricks')
		.add('twigs:cracked_bricks')
		.add('clayworks:chiseled_bricks')
		
	event.get('raspberry_flavoured:brick_half')
		.add('minecraft:brick_slab')
		.add('minecraft:brick_wall')
		
	event.get('raspberry_flavoured:mossy_brick')
		.add('twigs:mossy_bricks')
		.add('twigs:mossy_brick_stairs')
		
	event.get('raspberry_flavoured:mossy_brick_half')
		.add('twigs:mossy_brick_slab')
		.add('twigs:mossy_brick_wall')
		
	event.get('raspberry_flavoured:nether_brick')
		.add('minecraft:nether_bricks')
		.add('minecraft:cracked_nether_bricks')
		.add('minecraft:chiseled_nether_bricks')
		.add('minecraft:nether_brick_stairs')
		.add('mynethersdelight:nether_bricks_cabinet')
		
	event.get('raspberry_flavoured:nether_brick_half')
		.add('minecraft:nether_brick_slab')
		.add('minecraft:nether_brick_wall')
		
	event.get('raspberry_flavoured:red_nether_brick')
		.add('minecraft:red_nether_bricks')
		.add('minecraft:red_nether_brick_stairs')
		
	event.get('raspberry_flavoured:red_nether_brick_half')
		.add('minecraft:red_nether_brick_slab')
		.add('minecraft:red_nether_brick_wall')
		
	event.get('raspberry_flavoured:blue_nether_brick')
		.add('quark:blue_nether_bricks')
		.add('quark:blue_nether_bricks_stairs')
		
	event.get('raspberry_flavoured:blue_nether_brick_half')
		.add('quark:blue_nether_bricks_slab')
		.add('quark:blue_nether_bricks_wall')
		
	event.get('raspberry_flavoured:silt_brick')
		.add('twigs:silt_bricks')
		.add('twigs:silt_brick_stairs')
		.add('twigs:mixed_silt_bricks')
		.add('twigs:chiseled_silt_bricks')
		.add('twigs:cracked_silt_bricks')
		.add('kubejs:chiseled_silt_bricks')
		
	event.get('raspberry_flavoured:silt_brick_half')
		.add('twigs:silt_brick_slab')
		.add('twigs:silt_brick_wall')
		
	event.get('raspberry_flavoured:ash_brick')
		.add('supplementaries:ash_bricks')
		.add('supplementaries:ash_bricks_stairs')
		.add('kubejs:trimmed_ash_bricks')
		.add('kubejs:chiseled_ash_bricks')
		
	event.get('raspberry_flavoured:ash_brick_half')
		.add('supplementaries:ash_bricks_slab')
		.add('supplementaries:ash_bricks_wall')
		
	event.get('raspberry_flavoured:mud')
		.add('minecraft:packed_mud')
		.add('minecraft:mud_bricks')
		.add('minecraft:mud_brick_stairs')
		.add('environmental:smooth_mud')
		.add('environmental:chiseled_mud_bricks')
		.add('quark:carved_mud_bricks')
		.add('quark:mud_pillar')
		.add('quark:mud_brick_lattice')
		
	event.get('raspberry_flavoured:mud_half')
		.add('minecraft:mud_brick_slab')
		.add('environmental:smooth_mud_slab')
		.add('minecraft:mud_brick_wall')
		
	event.get('raspberry_flavoured:prismarine')
		.add('minecraft:prismarine')
		.add('minecraft:prismarine_stairs')
		.add('minecraft:prismarine_bricks')
		.add('minecraft:prismarine_brick_stairs')
		
	event.get('raspberry_flavoured:prismarine_half')
		.add('minecraft:prismarine_slab')
		.add('minecraft:prismarine_brick_slab')
		.add('minecraft:prismarine_wall')
		
	event.get('raspberry_flavoured:dark_prismarine')
		.add('minecraft:dark_prismarine')
		.add('minecraft:dark_prismarine_stairs')
		
	event.get('raspberry_flavoured:dark_prismarine_half')
		.add('minecraft:dark_prismarine_slab')
		
	event.get('raspberry_flavoured:luminous_prismarine')
		.add('upgrade_aquatic:luminous_prismarine')
		.add('upgrade_aquatic:luminous_prismarine_stairs')
		
	event.get('raspberry_flavoured:luminous_prismarine_half')
		.add('upgrade_aquatic:luminous_prismarine_slab')
		
	event.get('raspberry_flavoured:rock_salt')
		.add('spelunkery:rock_salt_block')
		.add('spelunkery:rock_salt_stairs')
		.add('spelunkery:polished_rock_salt')
		.add('spelunkery:polished_rock_salt_stairs')
		.add('spelunkery:rock_salt_bricks')
		.add('spelunkery:rock_salt_brick_stairs')
		
	event.get('raspberry_flavoured:rock_salt_half')
		.add('spelunkery:rock_salt_slab')
		.add('spelunkery:polished_rock_salt_slab')
		.add('spelunkery:rock_salt_brick_slab')
		.add('spelunkery:rock_salt_wall')
		.add('spelunkery:polished_rock_salt_wall')
		.add('spelunkery:rock_salt_brick_wall')
		
	event.get('raspberry_flavoured:lapis')
		.add('spelunkery:rough_lazurite_block')
		.add('kubejs:lazurite_stairs')
		.add('minecraft:emerald_block')
		.add('kubejs:lapis_stairs')
		.add('caverns_and_chasms:lapis_bricks')
		.add('caverns_and_chasms:lapis_brick_stairs')
		.add('caverns_and_chasms:lapis_pillar')
		
	event.get('raspberry_flavoured:lapis_half')
		.add('kubejs:lazurite_slab')
		.add('kubejs:lapis_slab')
		.add('caverns_and_chasms:lapis_brick_slab')
		.add('kubejs:lazurite_wall')
		.add('kubejs:lapis_wall')
		.add('caverns_and_chasms:lapis_brick_wall')
		
	event.get('raspberry_flavoured:gravel')
		.add('minecraft:gravel')
		.add('supplementaries:raked_gravel')
		.add('twigs:gravel_bricks')
		.add('twigs:gravel_brick_stairs')
		
	event.get('raspberry_flavoured:gravel_half')
		.add('twigs:gravel_brick_slab')
		.add('twigs:gravel_brick_wall')
		
	event.get('raspberry_flavoured:deepslate_gravel')
		.add('raspberry:deepslate_gravel')
		.add('raspberry:raked_deepslate_gravel')
		.add('kubejs:deepslate_gravel_bricks')
		.add('kubejs:deepslate_gravel_brick_stairs')
		
	event.get('raspberry_flavoured:deepslate_gravel_half')
		.add('kubejs:deepslate_gravel_brick_slab')
		.add('kubejs:deepslate_gravel_brick_wall')
		
	event.get('raspberry_flavoured:blackstone_gravel')
		.add('raspberry:blackstone_gravel')
		.add('raspberry:raked_blackstone_gravel')
		.add('kubejs:blackstone_gravel_bricks')
		.add('kubejs:blackstone_gravel_brick_stairs')
		
	event.get('raspberry_flavoured:blackstone_gravel_half')
		.add('kubejs:blackstone_gravel_brick_slab')
		.add('kubejs:blackstone_gravel_brick_wall')
		
	event.get('raspberry_flavoured:steel')
		.add('kubejs:polished_steel')
		.add('alloyed:steel_sheet_metal')
		.add('alloyed:steel_sheet_stairs')
		
	event.get('raspberry_flavoured:steel_half')
		.add('alloyed:steel_sheet_slab')
		
	event.get('raspberry_flavoured:obsidian')
		.add('minecraft:obsidian')
		.add('frame_changer:chiseled_obsidian')
		.add('frame_changer:obsidian_pillar')
		.add('frame_changer:polished_obsidian_stairs')
		.add('frame_changer:polished_obsidian')
		.add('frame_changer:obsidian_brick_stairs')
		.add('frame_changer:obsidian_bricks')
		
	event.get('raspberry_flavoured:obsidian_half')
		.add('frame_changer:polished_obsidian_slab')
		.add('frame_changer:obsidian_brick_slab')
		.add('frame_changer:polished_obsidian_wall')
		.add('frame_changer:obsidian_brick_wall')
		
	event.get('raspberry_flavoured:crying_obsidian')
		.add('minecraft:crying_obsidian')
		.add('frame_changer:crying_chiseled_obsidian')
		.add('frame_changer:crying_obsidian_pillar')
		.add('frame_changer:crying_polished_obsidian_stairs')
		.add('frame_changer:crying_polished_obsidian')
		.add('frame_changer:crying_obsidian_brick_stairs')
		.add('frame_changer:crying_obsidian_bricks')
		
	event.get('raspberry_flavoured:crying_obsidian_half')
		.add('frame_changer:crying_polished_obsidian_slab')
		.add('frame_changer:crying_obsidian_brick_slab')
		.add('frame_changer:crying_polished_obsidian_wall')
		.add('frame_changer:crying_obsidian_brick_wall')
		
	event.get('raspberry_flavoured:lachryte')
		.add('kubejs:lachryte')
		.add('kubejs:lachryte_stairs')
		.add('kubejs:polished_lachryte')
		.add('kubejs:polished_lachryte_stairs')
		.add('kubejs:chiseled_lachryte')
		.add('kubejs:lachryte_bricks')
		.add('kubejs:lachryte_brick_stairs')
		
	event.get('raspberry_flavoured:lachryte_half')
		.add('kubejs:lachryte_slab')
		.add('kubejs:polished_lachryte_slab')
		.add('kubejs:lachryte_brick_slab')
		.add('kubejs:lachryte_wall')
		.add('kubejs:polished_lachryte_wall')
		.add('kubejs:lachryte_brick_wall')
		
	event.get('raspberry_flavoured:exolite')
		.add('endergetic:poismoss')
		.add('kubejs:cobbled_exolite')
		.add('kubejs:exolite')
		.add('kubejs:chiseled_exolite')
		.add('kubejs:chiseled_exolite_tiles')
		.add('architects_palette:myonite_stairs')
		.add('architects_palette:myonite_brick_stairs')
		.add('architects_palette:mushy_myonite_bricks')
		.add('architects_palette:mushy_myonite_brick_stairs')
		.add('architects_palette:cerebral_block')
		.add('architects_palette:cerebral_stairs')
		.add('architects_palette:cerebral_pillar')
		.add('architects_palette:cerebral_tiles')
		.add('architects_palette:cerebral_tile_stairs')
		
	event.get('raspberry_flavoured:exolite_half')
		.add('architects_palette:myonite_slab')
		.add('architects_palette:myonite_wall')
		.add('architects_palette:myonite_brick_slab')
		.add('architects_palette:myonite_brick_wall')
		.add('architects_palette:mushy_myonite_brick_slab')
		.add('architects_palette:mushy_myonite_brick_wall')
		.add('architects_palette:cerebral_slab')
		.add('architects_palette:cerebral_wall')
		.add('architects_palette:cerebral_tile_slab')
		.add('architects_palette:cerebral_tile_wall')
		
	event.get('raspberry_flavoured:glowstone')
		.add('minecraft:glowstone')
		.add('architects_palette:polished_glowstone')
		.add('architects_palette:runic_glowstone')
		
	event.get('raspberry_flavoured:glowstone_half')
		.add('architects_palette:polished_glowstone_slab')
		.add('architects_palette:polished_glowstone_wall')
		
	event.get('raspberry_flavoured:copycat')
		.add('copycats:copycat_block')
		.add('copycats:copycat_stairs')
		
	event.get('raspberry_flavoured:copycat_half')
		.add('copycats:copycat_slab')
		.add('copycats:copycat_fence')
		.add('copycats:copycat_fence_gate')
		.add('copycats:copycat_wall')
		
	event.get('raspberry_flavoured:copycat_quarter')
		.add('create:copycat_panel')
		.add('create:copycat_step')
		.add('copycats:copycat_vertical_step')
		.add('copycats:copycat_beam')
		
	event.get('raspberry_flavoured:terracotta')
		.add('minecraft:terracotta')
		.add('clayworks:terracotta_stairs')
		.add('clayworks:terracotta_bricks')
		.add('clayworks:terracotta_brick_stairs')
		.add('clayworks:chiseled_terracotta_bricks')
		.add('quark:shingles')
		.add('quark:shingles_stairs')
		.add('clayworks:glazed_terracotta')
		
	event.get('raspberry_flavoured:terracotta_half')
		.add('clayworks:terracotta_slab')
		.add('clayworks:terracotta_brick_slab')
		.add('quark:shingles_slab')
		.add('clayworks:terracotta_wall')
		.add('clayworks:terracotta_brick_wall')
		
	event.get('raspberry_flavoured:white_terracotta')
		.add('minecraft:white_terracotta')
		.add('clayworks:white_terracotta_stairs')
		.add('clayworks:white_terracotta_bricks')
		.add('clayworks:white_terracotta_brick_stairs')
		.add('clayworks:chiseled_white_terracotta_bricks')
		.add('quark:white_shingles')
		.add('quark:white_shingles_stairs')
		.add('minecraft:white_glazed_terracotta')
		
	event.get('raspberry_flavoured:white_terracotta_half')
		.add('clayworks:white_terracotta_slab')
		.add('clayworks:white_terracotta_brick_slab')
		.add('quark:white_shingles_slab')
		.add('clayworks:white_terracotta_wall')
		.add('clayworks:white_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:orange_terracotta')
		.add('minecraft:orange_terracotta')
		.add('clayworks:orange_terracotta_stairs')
		.add('clayworks:orange_terracotta_bricks')
		.add('clayworks:orange_terracotta_brick_stairs')
		.add('clayworks:chiseled_orange_terracotta_bricks')
		.add('quark:orange_shingles')
		.add('quark:orange_shingles_stairs')
		.add('minecraft:orange_glazed_terracotta')
		
	event.get('raspberry_flavoured:orange_terracotta_half')
		.add('clayworks:orange_terracotta_slab')
		.add('clayworks:orange_terracotta_brick_slab')
		.add('quark:orange_shingles_slab')
		.add('clayworks:orange_terracotta_wall')
		.add('clayworks:orange_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:magenta_terracotta')
		.add('minecraft:magenta_terracotta')
		.add('clayworks:magenta_terracotta_stairs')
		.add('clayworks:magenta_terracotta_bricks')
		.add('clayworks:magenta_terracotta_brick_stairs')
		.add('clayworks:chiseled_magenta_terracotta_bricks')
		.add('quark:magenta_shingles')
		.add('quark:magenta_shingles_stairs')
		.add('minecraft:magenta_glazed_terracotta')
		
	event.get('raspberry_flavoured:magenta_terracotta_half')
		.add('clayworks:magenta_terracotta_slab')
		.add('clayworks:magenta_terracotta_brick_slab')
		.add('quark:magenta_shingles_slab')
		.add('clayworks:magenta_terracotta_wall')
		.add('clayworks:magenta_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:light_blue_terracotta')
		.add('minecraft:light_blue_terracotta')
		.add('clayworks:light_blue_terracotta_stairs')
		.add('clayworks:light_blue_terracotta_bricks')
		.add('clayworks:light_blue_terracotta_brick_stairs')
		.add('clayworks:chiseled_light_blue_terracotta_bricks')
		.add('quark:light_blue_shingles')
		.add('quark:light_blue_shingles_stairs')
		.add('minecraft:light_blue_glazed_terracotta')
		
	event.get('raspberry_flavoured:light_blue_terracotta_half')
		.add('clayworks:light_blue_terracotta_slab')
		.add('clayworks:light_blue_terracotta_brick_slab')
		.add('quark:light_blue_shingles_slab')
		.add('clayworks:light_blue_terracotta_wall')
		.add('clayworks:light_blue_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:yellow_terracotta')
		.add('minecraft:yellow_terracotta')
		.add('clayworks:yellow_terracotta_stairs')
		.add('clayworks:yellow_terracotta_bricks')
		.add('clayworks:yellow_terracotta_brick_stairs')
		.add('clayworks:chiseled_yellow_terracotta_bricks')
		.add('quark:yellow_shingles')
		.add('quark:yellow_shingles_stairs')
		.add('minecraft:yellow_glazed_terracotta')
		
	event.get('raspberry_flavoured:yellow_terracotta_half')
		.add('clayworks:yellow_terracotta_slab')
		.add('clayworks:yellow_terracotta_brick_slab')
		.add('quark:yellow_shingles_slab')
		.add('clayworks:yellow_terracotta_wall')
		.add('clayworks:yellow_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:lime_terracotta')
		.add('minecraft:lime_terracotta')
		.add('clayworks:lime_terracotta_stairs')
		.add('clayworks:lime_terracotta_bricks')
		.add('clayworks:lime_terracotta_brick_stairs')
		.add('clayworks:chiseled_lime_terracotta_bricks')
		.add('quark:lime_shingles')
		.add('quark:lime_shingles_stairs')
		.add('minecraft:lime_glazed_terracotta')
		
	event.get('raspberry_flavoured:lime_terracotta_half')
		.add('clayworks:lime_terracotta_slab')
		.add('clayworks:lime_terracotta_brick_slab')
		.add('quark:lime_shingles_slab')
		.add('clayworks:lime_terracotta_wall')
		.add('clayworks:lime_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:pink_terracotta')
		.add('minecraft:pink_terracotta')
		.add('clayworks:pink_terracotta_stairs')
		.add('clayworks:pink_terracotta_bricks')
		.add('clayworks:pink_terracotta_brick_stairs')
		.add('clayworks:chiseled_pink_terracotta_bricks')
		.add('quark:pink_shingles')
		.add('quark:pink_shingles_stairs')
		.add('minecraft:pink_glazed_terracotta')
		
	event.get('raspberry_flavoured:pink_terracotta_half')
		.add('clayworks:pink_terracotta_slab')
		.add('clayworks:pink_terracotta_brick_slab')
		.add('quark:pink_shingles_slab')
		.add('clayworks:pink_terracotta_wall')
		.add('clayworks:pink_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:gray_terracotta')
		.add('minecraft:gray_terracotta')
		.add('clayworks:gray_terracotta_stairs')
		.add('clayworks:gray_terracotta_bricks')
		.add('clayworks:gray_terracotta_brick_stairs')
		.add('clayworks:chiseled_gray_terracotta_bricks')
		.add('quark:gray_shingles')
		.add('quark:gray_shingles_stairs')
		.add('minecraft:gray_glazed_terracotta')
		
	event.get('raspberry_flavoured:gray_terracotta_half')
		.add('clayworks:gray_terracotta_slab')
		.add('clayworks:gray_terracotta_brick_slab')
		.add('quark:gray_shingles_slab')
		.add('clayworks:gray_terracotta_wall')
		.add('clayworks:gray_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:light_gray_terracotta')
		.add('minecraft:light_gray_terracotta')
		.add('clayworks:light_gray_terracotta_stairs')
		.add('clayworks:light_gray_terracotta_bricks')
		.add('clayworks:light_gray_terracotta_brick_stairs')
		.add('clayworks:chiseled_light_gray_terracotta_bricks')
		.add('quark:light_gray_shingles')
		.add('quark:light_gray_shingles_stairs')
		.add('minecraft:light_gray_glazed_terracotta')
		
	event.get('raspberry_flavoured:light_gray_terracotta_half')
		.add('clayworks:light_gray_terracotta_slab')
		.add('clayworks:light_gray_terracotta_brick_slab')
		.add('quark:light_gray_shingles_slab')
		.add('clayworks:light_gray_terracotta_wall')
		.add('clayworks:light_gray_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:cyan_terracotta')
		.add('minecraft:cyan_terracotta')
		.add('clayworks:cyan_terracotta_stairs')
		.add('clayworks:cyan_terracotta_bricks')
		.add('clayworks:cyan_terracotta_brick_stairs')
		.add('clayworks:chiseled_cyan_terracotta_bricks')
		.add('quark:cyan_shingles')
		.add('quark:cyan_shingles_stairs')
		.add('minecraft:cyan_glazed_terracotta')
		
	event.get('raspberry_flavoured:cyan_terracotta_half')
		.add('clayworks:cyan_terracotta_slab')
		.add('clayworks:cyan_terracotta_brick_slab')
		.add('quark:cyan_shingles_slab')
		.add('clayworks:cyan_terracotta_wall')
		.add('clayworks:cyan_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:purple_terracotta')
		.add('minecraft:purple_terracotta')
		.add('clayworks:purple_terracotta_stairs')
		.add('clayworks:purple_terracotta_bricks')
		.add('clayworks:purple_terracotta_brick_stairs')
		.add('clayworks:chiseled_purple_terracotta_bricks')
		.add('quark:purple_shingles')
		.add('quark:purple_shingles_stairs')
		.add('minecraft:purple_glazed_terracotta')
		
	event.get('raspberry_flavoured:purple_terracotta_half')
		.add('clayworks:purple_terracotta_slab')
		.add('clayworks:purple_terracotta_brick_slab')
		.add('quark:purple_shingles_slab')
		.add('clayworks:purple_terracotta_wall')
		.add('clayworks:purple_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:blue_terracotta')
		.add('minecraft:blue_terracotta')
		.add('clayworks:blue_terracotta_stairs')
		.add('clayworks:blue_terracotta_bricks')
		.add('clayworks:blue_terracotta_brick_stairs')
		.add('clayworks:chiseled_blue_terracotta_bricks')
		.add('quark:blue_shingles')
		.add('quark:blue_shingles_stairs')
		.add('minecraft:blue_glazed_terracotta')
		
	event.get('raspberry_flavoured:blue_terracotta_half')
		.add('clayworks:blue_terracotta_slab')
		.add('clayworks:blue_terracotta_brick_slab')
		.add('quark:blue_shingles_slab')
		.add('clayworks:blue_terracotta_wall')
		.add('clayworks:blue_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:brown_terracotta')
		.add('minecraft:brown_terracotta')
		.add('clayworks:brown_terracotta_stairs')
		.add('clayworks:brown_terracotta_bricks')
		.add('clayworks:brown_terracotta_brick_stairs')
		.add('clayworks:chiseled_brown_terracotta_bricks')
		.add('quark:brown_shingles')
		.add('quark:brown_shingles_stairs')
		.add('minecraft:brown_glazed_terracotta')
		
	event.get('raspberry_flavoured:brown_terracotta_half')
		.add('clayworks:brown_terracotta_slab')
		.add('clayworks:brown_terracotta_brick_slab')
		.add('quark:brown_shingles_slab')
		.add('clayworks:brown_terracotta_wall')
		.add('clayworks:brown_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:green_terracotta')
		.add('minecraft:green_terracotta')
		.add('clayworks:green_terracotta_stairs')
		.add('clayworks:green_terracotta_bricks')
		.add('clayworks:green_terracotta_brick_stairs')
		.add('clayworks:chiseled_green_terracotta_bricks')
		.add('quark:green_shingles')
		.add('quark:green_shingles_stairs')
		.add('minecraft:green_glazed_terracotta')
		
	event.get('raspberry_flavoured:green_terracotta_half')
		.add('clayworks:green_terracotta_slab')
		.add('clayworks:green_terracotta_brick_slab')
		.add('quark:green_shingles_slab')
		.add('clayworks:green_terracotta_wall')
		.add('clayworks:green_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:red_terracotta')
		.add('minecraft:red_terracotta')
		.add('clayworks:red_terracotta_stairs')
		.add('clayworks:red_terracotta_bricks')
		.add('clayworks:red_terracotta_brick_stairs')
		.add('clayworks:chiseled_red_terracotta_bricks')
		.add('quark:red_shingles')
		.add('quark:red_shingles_stairs')
		.add('minecraft:red_glazed_terracotta')
		
	event.get('raspberry_flavoured:red_terracotta_half')
		.add('clayworks:red_terracotta_slab')
		.add('clayworks:red_terracotta_brick_slab')
		.add('quark:red_shingles_slab')
		.add('clayworks:red_terracotta_wall')
		.add('clayworks:red_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:black_terracotta')
		.add('minecraft:black_terracotta')
		.add('clayworks:black_terracotta_stairs')
		.add('clayworks:black_terracotta_bricks')
		.add('clayworks:black_terracotta_brick_stairs')
		.add('clayworks:chiseled_black_terracotta_bricks')
		.add('quark:black_shingles')
		.add('quark:black_shingles_stairs')
		.add('minecraft:black_glazed_terracotta')
		
	event.get('raspberry_flavoured:black_terracotta_half')
		.add('clayworks:black_terracotta_slab')
		.add('clayworks:black_terracotta_brick_slab')
		.add('quark:black_shingles_slab')
		.add('clayworks:black_terracotta_wall')
		.add('clayworks:black_terracotta_brick_wall')
		
	event.get('raspberry_flavoured:white_concrete')
		.add('minecraft:white_concrete')
		.add('moreconcrete:white_concrete_stairs')
		
	event.get('raspberry_flavoured:white_concrete_half')
		.add('moreconcrete:white_concrete_slab')
		.add('moreconcrete:white_concrete_wall')
		
	event.get('raspberry_flavoured:orange_concrete')
		.add('minecraft:orange_concrete')
		.add('moreconcrete:orange_concrete_stairs')
		
	event.get('raspberry_flavoured:orange_concrete_half')
		.add('moreconcrete:orange_concrete_slab')
		.add('moreconcrete:orange_concrete_wall')
		
	event.get('raspberry_flavoured:magenta_concrete')
		.add('minecraft:magenta_concrete')
		.add('moreconcrete:magenta_concrete_stairs')
		
	event.get('raspberry_flavoured:magenta_concrete_half')
		.add('moreconcrete:magenta_concrete_slab')
		.add('moreconcrete:magenta_concrete_wall')
		
	event.get('raspberry_flavoured:light_blue_concrete')
		.add('minecraft:light_blue_concrete')
		.add('moreconcrete:light_blue_concrete_stairs')
		
	event.get('raspberry_flavoured:light_blue_concrete_half')
		.add('moreconcrete:light_blue_concrete_slab')
		.add('moreconcrete:light_blue_concrete_wall')
		
	event.get('raspberry_flavoured:yellow_concrete')
		.add('minecraft:yellow_concrete')
		.add('moreconcrete:yellow_concrete_stairs')
		
	event.get('raspberry_flavoured:yellow_concrete_half')
		.add('moreconcrete:yellow_concrete_slab')
		.add('moreconcrete:yellow_concrete_wall')
		
	event.get('raspberry_flavoured:lime_concrete')
		.add('minecraft:lime_concrete')
		.add('moreconcrete:lime_concrete_stairs')
		
	event.get('raspberry_flavoured:lime_concrete_half')
		.add('moreconcrete:lime_concrete_slab')
		.add('moreconcrete:lime_concrete_wall')
		
	event.get('raspberry_flavoured:pink_concrete')
		.add('minecraft:pink_concrete')
		.add('moreconcrete:pink_concrete_stairs')
		
	event.get('raspberry_flavoured:pink_concrete_half')
		.add('moreconcrete:pink_concrete_slab')
		.add('moreconcrete:pink_concrete_wall')
		
	event.get('raspberry_flavoured:gray_concrete')
		.add('minecraft:gray_concrete')
		.add('moreconcrete:gray_concrete_stairs')
		
	event.get('raspberry_flavoured:gray_concrete_half')
		.add('moreconcrete:gray_concrete_slab')
		.add('moreconcrete:gray_concrete_wall')
		
	event.get('raspberry_flavoured:light_gray_concrete')
		.add('minecraft:light_gray_concrete')
		.add('moreconcrete:light_gray_concrete_stairs')
		
	event.get('raspberry_flavoured:light_gray_concrete_half')
		.add('moreconcrete:light_gray_concrete_slab')
		.add('moreconcrete:light_gray_concrete_wall')
		
	event.get('raspberry_flavoured:cyan_concrete')
		.add('minecraft:cyan_concrete')
		.add('moreconcrete:cyan_concrete_stairs')
		
	event.get('raspberry_flavoured:cyan_concrete_half')
		.add('moreconcrete:cyan_concrete_slab')
		.add('moreconcrete:cyan_concrete_wall')
		
	event.get('raspberry_flavoured:purple_concrete')
		.add('minecraft:purple_concrete')
		.add('moreconcrete:purple_concrete_stairs')
		
	event.get('raspberry_flavoured:purple_concrete_half')
		.add('moreconcrete:purple_concrete_slab')
		.add('moreconcrete:purple_concrete_wall')
		
	event.get('raspberry_flavoured:blue_concrete')
		.add('minecraft:blue_concrete')
		.add('moreconcrete:blue_concrete_stairs')
		
	event.get('raspberry_flavoured:blue_concrete_half')
		.add('moreconcrete:blue_concrete_slab')
		.add('moreconcrete:blue_concrete_wall')
		
	event.get('raspberry_flavoured:brown_concrete')
		.add('minecraft:brown_concrete')
		.add('moreconcrete:brown_concrete_stairs')
		
	event.get('raspberry_flavoured:brown_concrete_half')
		.add('moreconcrete:brown_concrete_slab')
		.add('moreconcrete:brown_concrete_wall')
		
	event.get('raspberry_flavoured:green_concrete')
		.add('minecraft:green_concrete')
		.add('moreconcrete:green_concrete_stairs')
		
	event.get('raspberry_flavoured:green_concrete_half')
		.add('moreconcrete:green_concrete_slab')
		.add('moreconcrete:green_concrete_wall')
		
	event.get('raspberry_flavoured:red_concrete')
		.add('minecraft:red_concrete')
		.add('moreconcrete:red_concrete_stairs')
		
	event.get('raspberry_flavoured:red_concrete_half')
		.add('moreconcrete:red_concrete_slab')
		.add('moreconcrete:red_concrete_wall')
		
	event.get('raspberry_flavoured:black_concrete')
		.add('minecraft:black_concrete')
		.add('moreconcrete:black_concrete_stairs')
		
	event.get('raspberry_flavoured:black_concrete_half')
		.add('moreconcrete:black_concrete_slab')
		.add('moreconcrete:black_concrete_wall')
		
	event.get('raspberry_flavoured:copper')
		.add('minecraft:copper_block')
		.add('minecraft:cut_copper')
		.add('minecraft:cut_copper_stairs')
		.add('kubejs:copper_pillar')
		.add('create:copper_shingles')
		.add('create:copper_shingle_stairs')
		.add('create:copper_tiles')
		.add('create:copper_tile_stairs')
		.add('copperandtuffbackport:copper_grate')
		
	event.get('raspberry_flavoured:exposed_copper')
		.add('minecraft:exposed_copper')
		.add('minecraft:exposed_cut_copper')
		.add('minecraft:exposed_cut_copper_stairs')
		.add('kubejs:exposed_copper_pillar')
		.add('create:exposed_copper_shingles')
		.add('create:exposed_copper_shingle_stairs')
		.add('create:exposed_copper_tiles')
		.add('create:exposed_copper_tile_stairs')
		.add('copperandtuffbackport:exposed_copper_grate')
		
	event.get('raspberry_flavoured:weathered_copper')
		.add('minecraft:weathered_copper')
		.add('minecraft:weathered_cut_copper')
		.add('minecraft:weathered_cut_copper_stairs')
		.add('kubejs:weathered_copper_pillar')
		.add('create:weathered_copper_shingles')
		.add('create:weathered_copper_shingle_stairs')
		.add('create:weathered_copper_tiles')
		.add('create:weathered_copper_tile_stairs')
		.add('copperandtuffbackport:weathered_copper_grate')
		
	event.get('raspberry_flavoured:oxidized_copper')
		.add('minecraft:oxidized_copper')
		.add('minecraft:oxidized_cut_copper')
		.add('minecraft:oxidized_cut_copper_stairs')
		.add('kubejs:oxidized_copper_pillar')
		.add('create:oxidized_copper_shingles')
		.add('create:oxidized_copper_shingle_stairs')
		.add('create:oxidized_copper_tiles')
		.add('create:oxidized_copper_tile_stairs')
		.add('copperandtuffbackport:oxidized_copper_grate')
		
	event.get('raspberry_flavoured:waxed_copper')
		.add('minecraft:waxed_copper_block')
		.add('minecraft:waxed_cut_copper')
		.add('minecraft:waxed_cut_copper_stairs')
		.add('kubejs:waxed_copper_pillar')
		.add('create:waxed_copper_shingles')
		.add('create:waxed_copper_shingle_stairs')
		.add('create:waxed_copper_tiles')
		.add('create:waxed_copper_tile_stairs')
		.add('copperandtuffbackport:waxed_copper_grate')
		
	event.get('raspberry_flavoured:waxed_exposed_copper')
		.add('minecraft:waxed_exposed_copper')
		.add('minecraft:waxed_exposed_cut_copper')
		.add('minecraft:waxed_exposed_cut_copper_stairs')
		.add('kubejs:waxed_exposed_copper_pillar')
		.add('create:waxed_exposed_copper_shingles')
		.add('create:waxed_exposed_copper_shingle_stairs')
		.add('create:waxed_exposed_copper_tiles')
		.add('create:waxed_exposed_copper_tile_stairs')
		.add('copperandtuffbackport:waxed_exposed_copper_grate')
		
	event.get('raspberry_flavoured:waxed_weathered_copper')
		.add('minecraft:waxed_weathered_copper')
		.add('minecraft:waxed_weathered_cut_copper')
		.add('minecraft:waxed_weathered_cut_copper_stairs')
		.add('kubejs:waxed_weathered_copper_pillar')
		.add('create:waxed_weathered_copper_shingles')
		.add('create:waxed_weathered_copper_shingle_stairs')
		.add('create:waxed_weathered_copper_tiles')
		.add('create:waxed_weathered_copper_tile_stairs')
		.add('copperandtuffbackport:waxed_weathered_copper_grate')
		
	event.get('raspberry_flavoured:waxed_oxidized_copper')
		.add('minecraft:waxed_oxidized_copper')
		.add('minecraft:waxed_oxidized_cut_copper')
		.add('minecraft:waxed_oxidized_cut_copper_stairs')
		.add('kubejs:waxed_oxidized_copper_pillar')
		.add('create:waxed_oxidized_copper_shingles')
		.add('create:waxed_oxidized_copper_shingle_stairs')
		.add('create:waxed_oxidized_copper_tiles')
		.add('create:waxed_oxidized_copper_tile_stairs')
		.add('copperandtuffbackport:waxed_oxidized_copper_grate')
		
	event.get('raspberry_flavoured:copper_half')
		.add('minecraft:cut_copper_slab')
		.add('create:copper_shingle_slab')
		.add('create:copper_tile_slab')
		
	event.get('raspberry_flavoured:exposed_copper_half')
		.add('minecraft:exposed_cut_copper_slab')
		.add('create:exposed_copper_shingle_slab')
		.add('create:exposed_copper_tile_slab')
		
	event.get('raspberry_flavoured:weathered_copper_half')
		.add('minecraft:weathered_cut_copper_slab')
		.add('create:weathered_copper_shingle_slab')
		.add('create:weathered_copper_tile_slab')
		
	event.get('raspberry_flavoured:oxidized_copper_half')
		.add('minecraft:oxidized_cut_copper_slab')
		.add('create:oxidized_copper_shingle_slab')
		.add('create:oxidized_copper_tile_slab')
		
	event.get('raspberry_flavoured:waxed_copper_half')
		.add('minecraft:waxed_cut_copper_slab')
		.add('create:waxed_copper_shingle_slab')
		.add('create:waxed_copper_tile_slab')
		
	event.get('raspberry_flavoured:waxed_exposed_copper_half')
		.add('minecraft:waxed_exposed_cut_copper_slab')
		.add('create:waxed_exposed_copper_shingle_slab')
		.add('create:waxed_exposed_copper_tile_slab')
		
	event.get('raspberry_flavoured:waxed_weathered_copper_half')
		.add('minecraft:waxed_weathered_cut_copper_slab')
		.add('create:waxed_weathered_copper_shingle_slab')
		.add('create:waxed_weathered_copper_tile_slab')
		
	event.get('raspberry_flavoured:waxed_oxidized_copper_half')
		.add('minecraft:waxed_oxidized_cut_copper_slab')
		.add('create:waxed_oxidized_copper_shingle_slab')
		.add('create:waxed_oxidized_copper_tile_slab')
})

ServerEvents.tags('block', event => {
	event.get('raspberry_flavoured:logs')
		.add('minecraft:oak_log')
		.add('minecraft:spruce_log')
		.add('minecraft:birch_log')
		.add('minecraft:jungle_log')
		.add('minecraft:acacia_log')
		.add('minecraft:dark_oak_log')
		.add('minecraft:mangrove_log')
		.add('minecraft:crimson_stem')
		.add('minecraft:warped_stem')
		.add('architects_palette:twisted_log')
		.add('ecologics:coconut_log')
		.add('ecologics:azalea_log')
		.add('atmospheric:rosewood_log')
		.add('atmospheric:morado_log')
		.add('atmospheric:yucca_log')
		.add('atmospheric:watchful_aspen_log')
		.add('autumnity:maple_log')
		.add('environmental:willow_log')
		.add('environmental:cherry_log')
		.add('environmental:wisteria_log')
		.add('upgrade_aquatic:driftwood_log')
		.add('upgrade_aquatic:river_log')
		.add('windswept:chestnut_log')
		.add('culturaldelights:avocado_log')
		
	event.get('raspberry_flavoured:wood')
		.add('minecraft:oak_wood')
		.add('minecraft:spruce_wood')
		.add('minecraft:birch_wood')
		.add('minecraft:jungle_wood')
		.add('minecraft:acacia_wood')
		.add('minecraft:dark_oak_wood')
		.add('minecraft:mangrove_wood')
		.add('minecraft:crimson_hyphae')
		.add('minecraft:warped_hyphae')
		.add('architects_palette:twisted_wood')
		.add('ecologics:coconut_wood')
		.add('ecologics:azalea_wood')
		.add('atmospheric:rosewood')
		.add('atmospheric:morado_wood')
		.add('atmospheric:yucca_wood')
		.add('autumnity:maple_wood')
		.add('environmental:willow_wood')
		.add('environmental:cherry_wood')
		.add('environmental:wisteria_wood')
		.add('upgrade_aquatic:driftwood')
		.add('upgrade_aquatic:river_wood')
		.add('windswept:chestnut_wood')
		.add('culturaldelights:avocado_wood')
		
	event.get('raspberry_flavoured:stripped_logs')
		.add('minecraft:stripped_oak_log')
		.add('minecraft:stripped_spruce_log')
		.add('minecraft:stripped_birch_log')
		.add('minecraft:stripped_jungle_log')
		.add('minecraft:stripped_acacia_log')
		.add('minecraft:stripped_dark_oak_log')
		.add('minecraft:stripped_mangrove_log')
		.add('minecraft:stripped_crimson_stem')
		.add('minecraft:stripped_warped_stem')
		.add('architects_palette:stripped_twisted_log')
		.add('ecologics:stripped_coconut_log')
		.add('ecologics:stripped_azalea_log')
		.add('atmospheric:stripped_rosewood_log')
		.add('atmospheric:stripped_morado_log')
		.add('atmospheric:stripped_yucca_log')
		.add('kubejs:latex_jungle_log')
		.add('kubejs:latex_rosewood_log')
		.add('autumnity:stripped_maple_log')
		.add('autumnity:sappy_maple_log')
		.add('environmental:stripped_willow_log')
		.add('environmental:stripped_cherry_log')
		.add('environmental:stripped_wisteria_log')
		.add('upgrade_aquatic:stripped_driftwood_log')
		.add('upgrade_aquatic:stripped_river_log')
		.add('windswept:stripped_chestnut_log')
		
	event.get('raspberry_flavoured:stripped_wood')
		.add('minecraft:stripped_oak_wood')
		.add('minecraft:stripped_spruce_wood')
		.add('minecraft:stripped_birch_wood')
		.add('minecraft:stripped_jungle_wood')
		.add('minecraft:stripped_acacia_wood')
		.add('minecraft:stripped_dark_oak_wood')
		.add('minecraft:stripped_mangrove_wood')
		.add('minecraft:stripped_crimson_hyphae')
		.add('minecraft:stripped_warped_hyphae')
		.add('architects_palette:stripped_twisted_wood')
		.add('ecologics:stripped_coconut_wood')
		.add('ecologics:stripped_azalea_wood')
		.add('atmospheric:stripped_rosewood')
		.add('atmospheric:stripped_morado_wood')
		.add('atmospheric:stripped_yucca_wood')
		.add('kubejs:latex_jungle_wood')
		.add('kubejs:latex_rosewood')
		.add('autumnity:stripped_maple_wood')
		.add('autumnity:sappy_maple_wood')
		.add('environmental:stripped_willow_wood')
		.add('environmental:stripped_cherry_wood')
		.add('environmental:stripped_wisteria_wood')
		.add('upgrade_aquatic:stripped_driftwood')
		.add('upgrade_aquatic:stripped_river_wood')
		.add('windswept:stripped_chestnut_wood')
		
	event.get('raspberry_flavoured:all_wood_logs')
		.add('#raspberry_flavoured:logs')
		.add('#raspberry_flavoured:stripped_logs')
		.add('#raspberry_flavoured:wood')
		.add('#raspberry_flavoured:stripped_wood')
		
	event.get('raspberry_flavoured:driftwood')
		.add('upgrade_aquatic:driftwood_log')
		.add('upgrade_aquatic:driftwood')
		.add('upgrade_aquatic:stripped_driftwood_log')
		.add('upgrade_aquatic:stripped_driftwood')
})