// priority: 0

ServerEvents.recipes(event => {
	// Hammer
	event.recipes.farmersdelight.cutting('wooden_pickaxe', 'another_furniture:furniture_hammer', ['5x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('wooden_shovel', 'another_furniture:furniture_hammer', ['3x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('wooden_hoe', 'another_furniture:furniture_hammer', ['4x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('wooden_axe', 'another_furniture:furniture_hammer', ['5x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('wooden_sword', 'another_furniture:furniture_hammer', ['4x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('farmersdelight:flint_knife', 'another_furniture:furniture_hammer', [Item.of('flint').withChance(0.25), Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('kubejs:bone_knife', 'another_furniture:furniture_hammer', ['2x bone_meal', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('golden_pickaxe', 'another_furniture:furniture_hammer', ['6x gold_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_shovel', 'another_furniture:furniture_hammer', ['2x gold_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_hoe', 'another_furniture:furniture_hammer', ['4x gold_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_axe', 'another_furniture:furniture_hammer', ['6x gold_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_sword', 'another_furniture:furniture_hammer', ['4x gold_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('farmersdelight:golden_knife', 'another_furniture:furniture_hammer', ['2x gold_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('stone_pickaxe', 'another_furniture:furniture_hammer', ['6x create:copper_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('stone_shovel', 'another_furniture:furniture_hammer', ['2x create:copper_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('stone_hoe', 'another_furniture:furniture_hammer', ['4x create:copper_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('stone_axe', 'another_furniture:furniture_hammer', ['6x create:copper_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('stone_sword', 'another_furniture:furniture_hammer', ['4x create:copper_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('kubejs:copper_knife', 'another_furniture:furniture_hammer', ['2x create:copper_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('iron_pickaxe', 'another_furniture:furniture_hammer', ['6x iron_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_shovel', 'another_furniture:furniture_hammer', ['2x iron_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_hoe', 'another_furniture:furniture_hammer', ['4x iron_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_axe', 'another_furniture:furniture_hammer', ['6x iron_nugget', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_sword', 'another_furniture:furniture_hammer', ['4x iron_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('farmersdelight:iron_knife', 'another_furniture:furniture_hammer', ['2x iron_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('diamond_pickaxe', 'another_furniture:furniture_hammer', ['6x spelunkery:diamond_shard', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_shovel', 'another_furniture:furniture_hammer', ['2x spelunkery:diamond_shard', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_hoe', 'another_furniture:furniture_hammer', ['4x spelunkery:diamond_shard', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_axe', 'another_furniture:furniture_hammer', ['6x spelunkery:diamond_shard', '1x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_sword', 'another_furniture:furniture_hammer', ['4x spelunkery:diamond_shard', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('farmersdelight:diamond_knife', 'another_furniture:furniture_hammer', ['2x spelunkery:diamond_shard', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('golden_helmet', 'another_furniture:furniture_hammer', ['10x gold_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_chestplate', 'another_furniture:furniture_hammer', ['16x gold_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_leggings', 'another_furniture:furniture_hammer', ['14x gold_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_boots', 'another_furniture:furniture_hammer', ['8x gold_nugget'], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('chainmail_helmet', 'another_furniture:furniture_hammer', ['1x chain'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('chainmail_chestplate', 'another_furniture:furniture_hammer', ['2x chain'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('chainmail_leggings', 'another_furniture:furniture_hammer', ['2x chain'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('chainmail_boots', 'another_furniture:furniture_hammer', ['1x chain'], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('copperized:copper_helmet', 'another_furniture:furniture_hammer', ['10x create:copper_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('copperized:copper_chestplate', 'another_furniture:furniture_hammer', ['16x create:copper_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('copperized:copper_leggings', 'another_furniture:furniture_hammer', ['14x create:copper_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('copperized:copper_boots', 'another_furniture:furniture_hammer', ['8x create:copper_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:copper_diving_helmet', 'another_furniture:furniture_hammer', ['10x create:copper_nugget', 'quark:clear_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:copper_diving_boots', 'another_furniture:furniture_hammer', ['8x create:copper_nugget', Item.of('create:andesite_alloy').withChance(0.25)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:copper_backtank', 'another_furniture:furniture_hammer', ['24x create:copper_nugget', 'create:andesite_alloy'], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('iron_helmet', 'another_furniture:furniture_hammer', ['10x iron_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_chestplate', 'another_furniture:furniture_hammer', ['16x iron_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_leggings', 'another_furniture:furniture_hammer', ['14x iron_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_boots', 'another_furniture:furniture_hammer', ['8x iron_nugget'], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('diamond_helmet', 'another_furniture:furniture_hammer', ['10x spelunkery:diamond_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_chestplate', 'another_furniture:furniture_hammer', ['16x spelunkery:diamond_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_leggings', 'another_furniture:furniture_hammer', ['14x spelunkery:diamond_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_boots', 'another_furniture:furniture_hammer', ['9x spelunkery:diamond_shard'], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('turtle_helmet', 'another_furniture:furniture_hammer', ['scute'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('autumnity:snail_shell_chestplate', 'another_furniture:furniture_hammer', ['2x autumnity:snail_shell_piece'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('environmental:yak_pants', '#forge:shears', ['2x environmental:yak_hair'])
	
	event.recipes.farmersdelight.cutting('kubejs:copper_horse_armor', 'another_furniture:furniture_hammer', ['12x create:copper_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('iron_horse_armor', 'another_furniture:furniture_hammer', ['12x iron_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('golden_horse_armor', 'another_furniture:furniture_hammer', ['12x gold_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('diamond_horse_armor', 'another_furniture:furniture_hammer', ['12x spelunkery:diamond_shard', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('shieldexp:wooden_shield', 'another_furniture:furniture_hammer', ['6x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('shieldexp:golden_shield', 'another_furniture:furniture_hammer', ['8x create:copper_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('shield', 'another_furniture:furniture_hammer', ['8x iron_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('fishing_rod', 'another_furniture:furniture_hammer', ['1x stick', Item.of('string').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('carrot_on_a_stick', 'another_furniture:furniture_hammer', ['1x stick', Item.of('string').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('warped_fungus_on_a_stick', 'another_furniture:furniture_hammer', ['1x stick', Item.of('string').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('aquaculture:iron_fishing_rod', 'another_furniture:furniture_hammer', ['4x iron_nugget', Item.of('stick').withChance(0.5), Item.of('string').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('naturalist:bug_net', 'another_furniture:furniture_hammer', ['1x bamboo', Item.of('string').withChance(0.75)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('compass', 'another_furniture:furniture_hammer', ['8x iron_nugget', '2x spelunkery:cinnabar_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('caverns_and_chasms:depth_gauge', 'another_furniture:furniture_hammer', ['8x oreganized:lead_nugget', '2x spelunkery:cinnabar_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('clock', 'another_furniture:furniture_hammer', ['8x gold_nugget', '2x spelunkery:cinnabar_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('caverns_and_chasms:barometer', 'another_furniture:furniture_hammer', ['8x create:copper_nugget', '2x spelunkery:cinnabar_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('recovery_compass', 'another_furniture:furniture_hammer', ['8x iron_nugget', '2x spelunkery:cinnabar_shard', Item.of('quark:soul_bead').withChance(0.25)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('spelunkery:magnetic_compass', 'another_furniture:furniture_hammer', ['8x iron_nugget', '2x spelunkery:cinnabar_shard', '2x spelunkery:raw_magnetite_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('spyglass', 'another_furniture:furniture_hammer', ['4x create:copper_nugget', 'quark:clear_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('shears', 'another_furniture:furniture_hammer', ['4x create:copper_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('exposure:camera', 'another_furniture:furniture_hammer', ['8x gold_nugget', '3x stick', 'quark:clear_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('kubejs:copper_brush', 'another_furniture:furniture_hammer', ['2x create:copper_nugget', Item.of('stick').withChance(0.5), Item.of('feather').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('kubejs:copper_brush_wax', 'another_furniture:furniture_hammer', ['2x create:copper_nugget', Item.of('stick').withChance(0.5), Item.of('feather').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:super_glue', 'another_furniture:furniture_hammer', ['2x create:copper_nugget', Item.of('stick').withChance(0.5), Item.of('feather').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:wrench', 'another_furniture:furniture_hammer', ['6x gold_nugget', '2x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:extendo_grip', 'another_furniture:furniture_hammer', ['2x kubejs:rose_gold_nugget', '2x gold_nugget', '6x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('caverns_and_chasms:tuning_fork', 'another_furniture:furniture_hammer', ['4x alloyed:bronze_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('spelunkery:echo_fork', 'another_furniture:furniture_hammer', ['4x alloyed:bronze_nugget', Item.of('echo_shard').withChance(0.1)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('spelunkery:item_magnet', 'another_furniture:furniture_hammer', ['10x spelunkery:raw_magnetite_nugget', '9x oreganized:lead_nugget', '9x spelunkery:cinnabar_shard'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('quark:trowel', 'another_furniture:furniture_hammer', ['4x kubejs:rose_gold_nugget', Item.of('stick').withChance(0.5)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('quark:abacus', 'another_furniture:furniture_hammer', ['2x iron_nugget', '8x stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('supplementaries:bubble_blower', 'another_furniture:furniture_hammer', ['4x iron_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('supplementaries:slingshot', 'another_furniture:furniture_hammer', ['stick', Item.of('string').withChance(0.5), Item.of('rabbit_hide').withChance(0.25)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('supplementaries:flute', 'another_furniture:furniture_hammer', ['1x bamboo'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('supplementaries:wrench', 'another_furniture:furniture_hammer', ['8x create:copper_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('aquaculture:gold_hook', 'another_furniture:furniture_hammer', ['3x spelunkery:raw_magnetite_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('aquaculture:light_hook', 'another_furniture:furniture_hammer', ['3x create:copper_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('aquaculture:redstone_hook', 'another_furniture:furniture_hammer', ['3x create:zinc_nugget'], 'minecraft:entity.item.break')
	
	event.recipes.farmersdelight.cutting('bow', 'another_furniture:furniture_hammer', ['stick', 'string'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('crossbow', 'another_furniture:furniture_hammer', ['2x iron_nugget', 'stick', 'string'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('vc_gliders:paraglider_wood', 'another_furniture:furniture_hammer', ['2x stick', '3x string', Item.of('phantom_membrane').withChance(0.25)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('domesticationinnovation:collar_tag', 'another_furniture:furniture_hammer', ['2x create:copper_nugget', Item.of('chain').withChance(0.25)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:goggles', 'another_furniture:furniture_hammer', ['2x gold_nugget', '2x quark:clear_shard', Item.of('rabbit_hide').withChance(0.25)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('create:potato_cannon', 'another_furniture:furniture_hammer', ['9x create:copper_nugget', '2x gold_nugget', Item.of('create:andesite_alloy').withChance(0.25)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('caverns_and_chasms:kunai', 'another_furniture:furniture_hammer', [Item.of('oreganized:silver_nugget').withChance(0.3)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('oreganized:silver_mirror', 'another_furniture:furniture_hammer', ['10x gold_nugget', '4x oreganized:silver_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('bucket', 'another_furniture:furniture_hammer', ['6x iron_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('bowl', 'another_furniture:furniture_hammer', ['stick'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('glass_bottle', 'another_furniture:furniture_hammer', ['quark:clear_shard'], 'minecraft:block.glass.break')
	event.recipes.farmersdelight.cutting('brewinandchewin:tankard', 'another_furniture:furniture_hammer', ['stick', Item.of('iron_nugget').withChance(0.1)], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('supplementaries:globe', 'another_furniture:furniture_hammer', ['2x blue_dye', '2x green_dye', '8x gold_nugget'], 'minecraft:entity.item.break')
	event.recipes.farmersdelight.cutting('supplementaries:globe_sepia', 'another_furniture:furniture_hammer', ['4x brown_dye', '8x gold_nugget'], 'minecraft:entity.item.break')
	
	// Shears
	event.recipes.farmersdelight.cutting('saddle', '#forge:shears', ['rabbit_hide', Item.of('chain').withChance(0.25)])
	event.recipes.farmersdelight.cutting('leather_helmet', '#forge:shears', ['1x rabbit_hide'])
	event.recipes.farmersdelight.cutting('leather_chestplate', '#forge:shears', ['2x rabbit_hide'])
	event.recipes.farmersdelight.cutting('leather_leggings', '#forge:shears', ['2x rabbit_hide'])
	event.recipes.farmersdelight.cutting('leather_boots', '#forge:shears', ['1x rabbit_hide'])
	event.recipes.farmersdelight.cutting('windswept:snow_boots', '#forge:shears', ['2x rabbit_hide', Item.of('chain').withChance(0.5)])
	
	// Milling
	event.recipes.create.milling(['5x stick'], 'minecraft:wooden_pickaxe')
	event.recipes.create.milling(['3x stick'], 'minecraft:wooden_shovel')
	event.recipes.create.milling(['4x stick'], 'minecraft:wooden_hoe')
	event.recipes.create.milling(['5x stick'], 'minecraft:wooden_axe')
	event.recipes.create.milling(['4x stick'], 'minecraft:wooden_sword')
	event.recipes.create.milling([Item.of('flint').withChance(0.25), Item.of('stick').withChance(0.5)], 'farmersdelight:flint_knife')
	event.recipes.create.milling(['2x bone_meal', Item.of('stick').withChance(0.5)], 'kubejs:bone_knife')
	
	event.recipes.create.milling(['6x gold_nugget', '1x stick'], 'golden_pickaxe')
	event.recipes.create.milling(['2x gold_nugget', '1x stick'], 'golden_shovel')
	event.recipes.create.milling(['4x gold_nugget', '1x stick'], 'golden_hoe')
	event.recipes.create.milling(['6x gold_nugget', '1x stick'], 'golden_axe')
	event.recipes.create.milling(['4x gold_nugget', Item.of('stick').withChance(0.5)], 'golden_sword')
	event.recipes.create.milling(['2x gold_nugget', Item.of('stick').withChance(0.5)], 'farmersdelight:golden_knife')
	
	event.recipes.create.milling(['6x create:copper_nugget', '1x stick'], 'stone_pickaxe')
	event.recipes.create.milling(['2x create:copper_nugget', '1x stick'], 'stone_shovel')
	event.recipes.create.milling(['4x create:copper_nugget', '1x stick'], 'stone_hoe')
	event.recipes.create.milling(['6x create:copper_nugget', '1x stick'], 'stone_axe')
	event.recipes.create.milling(['4x create:copper_nugget', Item.of('stick').withChance(0.5)], 'stone_sword')
	event.recipes.create.milling(['2x create:copper_nugget', Item.of('stick').withChance(0.5)], 'kubejs:copper_knife')
	
	event.recipes.create.milling(['6x iron_nugget', '1x stick'], 'iron_pickaxe')
	event.recipes.create.milling(['2x iron_nugget', '1x stick'], 'iron_shovel')
	event.recipes.create.milling(['4x iron_nugget', '1x stick'], 'iron_hoe')
	event.recipes.create.milling(['6x iron_nugget', '1x stick'], 'iron_axe')
	event.recipes.create.milling(['4x iron_nugget', Item.of('stick').withChance(0.5)], 'iron_sword')
	event.recipes.create.milling(['2x iron_nugget', Item.of('stick').withChance(0.5)], 'farmersdelight:iron_knife')
	
	event.recipes.create.milling(['6x iron_nugget', '2x kubejs:rose_gold_nugget', '1x stick'], 'additionaladditions:rose_gold_pickaxe')
	event.recipes.create.milling(['2x iron_nugget', '2x kubejs:rose_gold_nugget', '1x stick'], 'additionaladditions:rose_gold_shovel')
	event.recipes.create.milling(['4x iron_nugget', '2x kubejs:rose_gold_nugget', '1x stick'], 'additionaladditions:rose_gold_hoe')
	event.recipes.create.milling(['6x iron_nugget', '2x kubejs:rose_gold_nugget', '1x stick'], 'additionaladditions:rose_gold_axe')
	event.recipes.create.milling(['4x iron_nugget', '2x kubejs:rose_gold_nugget', Item.of('stick').withChance(0.5)], 'additionaladditions:rose_gold_sword')
	event.recipes.create.milling(['2x iron_nugget', '2x kubejs:rose_gold_nugget', Item.of('stick').withChance(0.5)], 'kubejs:rose_gold_knife')
	event.recipes.create.milling(['4x iron_nugget', '6x kubejs:rose_gold_nugget', Item.of('stick').withChance(0.5)], 'kubejs:rose_gold_rapier')
	
	event.recipes.create.milling(['6x iron_nugget', '2x alloyed:steel_nugget', '1x stick'], 'alloyed:steel_pickaxe')
	event.recipes.create.milling(['2x iron_nugget', '2x alloyed:steel_nugget', '1x stick'], 'alloyed:steel_shovel')
	event.recipes.create.milling(['4x iron_nugget', '2x alloyed:steel_nugget', '1x stick'], 'alloyed:steel_hoe')
	event.recipes.create.milling(['6x iron_nugget', '2x alloyed:steel_nugget', '1x stick'], 'alloyed:steel_axe')
	event.recipes.create.milling(['4x iron_nugget', '2x alloyed:steel_nugget', Item.of('stick').withChance(0.5)], 'alloyed:steel_sword')
	event.recipes.create.milling(['2x iron_nugget', '2x alloyed:steel_nugget', Item.of('stick').withChance(0.5)], 'alloyed:steel_knife')
	event.recipes.create.milling(['6x iron_nugget', '6x alloyed:steel_nugget', Item.of('stick').withChance(0.5)], 'mace_backport:mace')
	
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '1x stick'], 'diamond_pickaxe')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '1x stick'], 'diamond_shovel')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '1x stick'], 'diamond_hoe')
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '1x stick'], 'diamond_axe')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', Item.of('stick').withChance(0.5)], 'diamond_sword')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', Item.of('stick').withChance(0.5)], 'farmersdelight:diamond_knife')
	
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '2x oreganized:electrum_nugget', '1x stick'], 'oreganized:electrum_pickaxe')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '2x oreganized:electrum_nugget', '1x stick'], 'oreganized:electrum_shovel')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '2x oreganized:electrum_nugget', '1x stick'], 'oreganized:electrum_hoe')
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '2x oreganized:electrum_nugget', '1x stick'], 'oreganized:electrum_axe')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '2x oreganized:electrum_nugget', Item.of('stick').withChance(0.5)], 'oreganized:electrum_sword')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '2x oreganized:electrum_nugget', Item.of('stick').withChance(0.5)], 'oreganized:electrum_knife')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '6x oreganized:electrum_nugget', Item.of('stick').withChance(0.5)], 'clash:spear')
	
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget', '1x stick'], 'caverns_and_chasms:necromium_pickaxe')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget', '1x stick'], 'caverns_and_chasms:necromium_shovel')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget', '1x stick'], 'caverns_and_chasms:necromium_hoe')
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget', '1x stick'], 'caverns_and_chasms:necromium_axe')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget', Item.of('stick').withChance(0.5)], 'caverns_and_chasms:necromium_sword')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget', Item.of('stick').withChance(0.5)], 'abnormals_delight:necromium_knife')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '6x caverns_and_chasms:necromium_nugget', Item.of('stick').withChance(0.5)], 'clash:greatblade')
	
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget', '1x stick'], 'netherite_pickaxe')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget', '1x stick'], 'netherite_shovel')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget', '1x stick'], 'netherite_hoe')
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget', '1x stick'], 'netherite_axe')
	event.recipes.create.milling(['4x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget', Item.of('stick').withChance(0.5)], 'netherite_sword')
	event.recipes.create.milling(['2x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget', Item.of('stick').withChance(0.5)], 'farmersdelight:netherite_knife')
	event.recipes.create.milling(['6x spelunkery:diamond_shard', '6x caverns_and_chasms:netherite_nugget', Item.of('stick').withChance(0.5)], 'clash:swept_axe')
	
	event.recipes.create.milling(['1x rabbit_hide'], 'leather_helmet')
	event.recipes.create.milling(['2x rabbit_hide'], 'leather_chestplate')
	event.recipes.create.milling(['2x rabbit_hide'], 'leather_leggings')
	event.recipes.create.milling(['1x rabbit_hide'], 'leather_boots')
	event.recipes.create.milling(['2x rabbit_hide', Item.of('chain').withChance(0.5)], 'windswept:snow_boots')
	
	event.recipes.create.milling(['10x gold_nugget'], 'golden_helmet')
	event.recipes.create.milling(['16x gold_nugget'], 'golden_chestplate')
	event.recipes.create.milling(['14x gold_nugget'], 'golden_leggings')
	event.recipes.create.milling(['8x gold_nugget'], 'golden_boots')
	
	event.recipes.create.milling(['1x chain'], 'chainmail_helmet')
	event.recipes.create.milling(['2x chain'], 'chainmail_chestplate')
	event.recipes.create.milling(['2x chain'], 'chainmail_leggings')
	event.recipes.create.milling(['1x chain'], 'chainmail_boots')
	
	event.recipes.create.milling(['10x create:copper_nugget'], 'copperized:copper_helmet')
	event.recipes.create.milling(['16x create:copper_nugget'], 'copperized:copper_chestplate')
	event.recipes.create.milling(['14x create:copper_nugget'], 'copperized:copper_leggings')
	event.recipes.create.milling(['8x create:copper_nugget'], 'copperized:copper_boots')
	event.recipes.create.milling(['10x create:copper_nugget', 'quark:clear_shard'], 'create:copper_diving_helmet')
	event.recipes.create.milling(['8x create:copper_nugget', Item.of('create:andesite_alloy').withChance(0.25)], 'create:copper_diving_boots')
	event.recipes.create.milling(['24x create:copper_nugget', 'create:andesite_alloy'], 'create:copper_backtank')
	
	event.recipes.create.milling(['10x iron_nugget'], 'iron_helmet')
	event.recipes.create.milling(['16x iron_nugget'], 'iron_chestplate')
	event.recipes.create.milling(['14x iron_nugget'], 'iron_leggings')
	event.recipes.create.milling(['8x iron_nugget'], 'iron_boots')
	
	event.recipes.create.milling(['10x iron_nugget', '2x kubejs:rose_gold_nugget'], 'additionaladditions:rose_gold_helmet')
	event.recipes.create.milling(['16x iron_nugget', '2x kubejs:rose_gold_nugget'], 'additionaladditions:rose_gold_chestplate')
	event.recipes.create.milling(['14x iron_nugget', '2x kubejs:rose_gold_nugget'], 'additionaladditions:rose_gold_leggings')
	event.recipes.create.milling(['8x iron_nugget', '2x kubejs:rose_gold_nugget'], 'additionaladditions:rose_gold_boots')
	
	event.recipes.create.milling(['10x iron_nugget', '2x alloyed:steel_nugget'], 'alloyed:steel_helmet')
	event.recipes.create.milling(['16x iron_nugget', '2x alloyed:steel_nugget'], 'alloyed:steel_chestplate')
	event.recipes.create.milling(['14x iron_nugget', '2x alloyed:steel_nugget'], 'alloyed:steel_leggings')
	event.recipes.create.milling(['8x iron_nugget', '2x alloyed:steel_nugget'], 'alloyed:steel_boots')
	
	event.recipes.create.milling(['10x spelunkery:diamond_shard'], 'diamond_helmet')
	event.recipes.create.milling(['16x spelunkery:diamond_shard'], 'diamond_chestplate')
	event.recipes.create.milling(['14x spelunkery:diamond_shard'], 'diamond_leggings')
	event.recipes.create.milling(['9x spelunkery:diamond_shard'], 'diamond_boots')
	
	event.recipes.create.milling(['10x spelunkery:diamond_shard', '2x oreganized:electrum_nugget'], 'oreganized:electrum_helmet')
	event.recipes.create.milling(['16x spelunkery:diamond_shard', '2x oreganized:electrum_nugget'], 'oreganized:electrum_chestplate')
	event.recipes.create.milling(['14x spelunkery:diamond_shard', '2x oreganized:electrum_nugget'], 'oreganized:electrum_leggings')
	event.recipes.create.milling(['8x spelunkery:diamond_shard', '2x oreganized:electrum_nugget'], 'oreganized:electrum_boots')
	
	event.recipes.create.milling(['10x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget'], 'caverns_and_chasms:necromium_helmet')
	event.recipes.create.milling(['16x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget'], 'caverns_and_chasms:necromium_chestplate')
	event.recipes.create.milling(['14x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget'], 'caverns_and_chasms:necromium_leggings')
	event.recipes.create.milling(['8x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget'], 'caverns_and_chasms:necromium_boots')
	
	event.recipes.create.milling(['10x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget'], 'netherite_helmet')
	event.recipes.create.milling(['16x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget'], 'netherite_chestplate')
	event.recipes.create.milling(['14x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget'], 'netherite_leggings')
	event.recipes.create.milling(['8x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget'], 'netherite_boots')
	
	event.recipes.create.milling(['1x savage_and_ravage:blast_proof_plating'], 'savage_and_ravage:griefer_helmet')
	event.recipes.create.milling(['2x savage_and_ravage:blast_proof_plating'], 'savage_and_ravage:griefer_chestplate')
	event.recipes.create.milling(['2x savage_and_ravage:blast_proof_plating'], 'savage_and_ravage:griefer_leggings')
	event.recipes.create.milling(['1x savage_and_ravage:blast_proof_plating'], 'savage_and_ravage:griefer_boots')
	
	event.recipes.create.milling(['1x caverns_and_chasms:sanguine_plating'], 'caverns_and_chasms:sanguine_helmet')
	event.recipes.create.milling(['2x caverns_and_chasms:sanguine_plating'], 'caverns_and_chasms:sanguine_chestplate')
	event.recipes.create.milling(['2x caverns_and_chasms:sanguine_plating'], 'caverns_and_chasms:sanguine_leggings')
	event.recipes.create.milling(['1x caverns_and_chasms:sanguine_plating'], 'caverns_and_chasms:sanguine_boots')
	
	event.recipes.create.milling(['scute'], 'turtle_helmet')
	event.recipes.create.milling(['2x autumnity:snail_shell_piece'], 'autumnity:snail_shell_chestplate')
	event.recipes.create.milling(['2x environmental:yak_hair'], 'environmental:yak_pants')
	
	event.recipes.create.milling(['12x create:copper_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'kubejs:copper_horse_armor')
	event.recipes.create.milling(['12x iron_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'iron_horse_armor')
	event.recipes.create.milling(['12x gold_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'golden_horse_armor')
	event.recipes.create.milling(['12x iron_nugget', '2x kubejs:rose_gold_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'kubejs:rose_gold_horse_armor')
	event.recipes.create.milling(['12x iron_nugget', '2x alloyed:steel_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'kubejs:steel_horse_armor')
	event.recipes.create.milling(['12x spelunkery:diamond_shard', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'diamond_horse_armor')
	event.recipes.create.milling(['12x spelunkery:diamond_shard', '2x oreganized:electrum_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'kubejs:electrum_horse_armor')
	event.recipes.create.milling(['12x spelunkery:diamond_shard', '2x caverns_and_chasms:necromium_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'kubejs:necromium_horse_armor')
	event.recipes.create.milling(['12x spelunkery:diamond_shard', '2x caverns_and_chasms:netherite_nugget', Item.of('kubejs:cloth_scrap').withChance(0.5)], 'kubejs:netherite_horse_armor')
	
	event.recipes.create.milling(['6x stick'], 'shieldexp:wooden_shield')
	event.recipes.create.milling(['8x create:copper_nugget', Item.of('stick').withChance(0.5)], 'shieldexp:golden_shield')
	event.recipes.create.milling(['8x iron_nugget', Item.of('stick').withChance(0.5)], 'shield')
	event.recipes.create.milling(['savage_and_ravage:blast_proof_plating', Item.of('stick').withChance(0.5)], 'shieldexp:griefer_shield')
	event.recipes.create.milling(['caverns_and_chasms:sanguine_plating', Item.of('stick').withChance(0.5)], 'shieldexp:iron_shield')
	
	event.recipes.create.milling(['rabbit_hide', Item.of('chain').withChance(0.25)], 'saddle')
	event.recipes.create.milling(['1x stick', Item.of('string').withChance(0.5)], 'fishing_rod')
	event.recipes.create.milling(['1x stick', Item.of('string').withChance(0.5)], 'carrot_on_a_stick')
	event.recipes.create.milling(['1x stick', Item.of('string').withChance(0.5)], 'warped_fungus_on_a_stick')
	event.recipes.create.milling(['4x iron_nugget', Item.of('stick').withChance(0.5), Item.of('string').withChance(0.5)], 'aquaculture:iron_fishing_rod')
	event.recipes.create.milling(['1x bamboo', Item.of('string').withChance(0.75)], 'naturalist:bug_net')
	event.recipes.create.milling(['8x iron_nugget', '2x spelunkery:cinnabar_shard'], 'compass')
	event.recipes.create.milling(['8x oreganized:lead_nugget', '2x spelunkery:cinnabar_shard'], 'caverns_and_chasms:depth_gauge')
	event.recipes.create.milling(['8x gold_nugget', '2x spelunkery:cinnabar_shard'], 'clock')
	event.recipes.create.milling(['8x create:copper_nugget', '2x spelunkery:cinnabar_shard'], 'caverns_and_chasms:barometer')
	event.recipes.create.milling(['8x iron_nugget', '2x spelunkery:cinnabar_shard', Item.of('quark:soul_bead').withChance(0.25)], 'recovery_compass')
	event.recipes.create.milling(['8x iron_nugget', '2x spelunkery:cinnabar_shard', '2x spelunkery:raw_magnetite_nugget'], 'spelunkery:magnetic_compass')
	event.recipes.create.milling(['4x create:copper_nugget', 'quark:clear_shard'], 'spyglass')
	event.recipes.create.milling(['4x create:copper_nugget'], 'shears')
	event.recipes.create.milling(['8x gold_nugget', '3x stick', 'quark:clear_shard'], 'exposure:camera')
	event.recipes.create.milling(['2x create:copper_nugget', Item.of('stick').withChance(0.5), Item.of('feather').withChance(0.5)], 'kubejs:copper_brush')
	event.recipes.create.milling(['2x create:copper_nugget', Item.of('stick').withChance(0.5), Item.of('feather').withChance(0.5)], 'kubejs:copper_brush_wax')
	event.recipes.create.milling(['2x create:copper_nugget', Item.of('stick').withChance(0.5), Item.of('feather').withChance(0.5)], 'create:super_glue')
	event.recipes.create.milling(['6x gold_nugget', '2x stick'], 'create:wrench')
	event.recipes.create.milling(['2x kubejs:rose_gold_nugget', '2x gold_nugget', '6x stick'], 'create:extendo_grip')
	event.recipes.create.milling(['6x quark:clear_shard', '2x create:brass_nugget', 'create:powdered_obsidian'], 'create:wand_of_symmetry')
	event.recipes.create.milling(['4x alloyed:bronze_nugget'], 'caverns_and_chasms:tuning_fork')
	event.recipes.create.milling(['4x alloyed:bronze_nugget', Item.of('echo_shard').withChance(0.1)], 'spelunkery:echo_fork')
	event.recipes.create.milling(['10x spelunkery:raw_magnetite_nugget', '9x oreganized:lead_nugget', '9x spelunkery:cinnabar_shard'], 'spelunkery:item_magnet')
	event.recipes.create.milling(['2x create:powdered_obsidian', Item.of('echo_shard').withChance(0.5), Item.of('quark:soul_bead').withChance(0.25)], 'quark:echorang')
	event.recipes.create.milling(['4x kubejs:rose_gold_nugget', Item.of('stick').withChance(0.5)], 'quark:trowel')
	event.recipes.create.milling(['2x iron_nugget', '8x stick'], 'quark:abacus')
	event.recipes.create.milling(['4x iron_nugget'], 'supplementaries:bubble_blower')
	event.recipes.create.milling(['stick', Item.of('string').withChance(0.5), Item.of('rabbit_hide').withChance(0.25)], 'supplementaries:slingshot')
	event.recipes.create.milling(['1x bamboo'], 'supplementaries:flute')
	event.recipes.create.milling(['8x create:copper_nugget'], 'supplementaries:wrench')
	event.recipes.create.milling(['3x spelunkery:raw_magnetite_nugget'], 'aquaculture:gold_hook')
	event.recipes.create.milling(['3x create:copper_nugget'], 'aquaculture:light_hook')
	event.recipes.create.milling(['3x alloyed:steel_nugget'], 'aquaculture:heavy_hook')
	event.recipes.create.milling(['3x create:copper_nugget', '3x alloyed:steel_nugget'], 'aquaculture:double_hook')
	event.recipes.create.milling(['3x create:zinc_nugget'], 'aquaculture:redstone_hook')
	
	event.recipes.create.milling(['stick', 'string'], 'bow')
	event.recipes.create.milling(['2x iron_nugget', 'stick', 'string'], 'crossbow')
	event.recipes.create.milling(['2x stick', '3x string', Item.of('phantom_membrane').withChance(0.25)], 'vc_gliders:paraglider_wood')
	event.recipes.create.milling(['upgrade_aquatic:thrasher_tooth', 'prismarine_shard'], 'trident')
	event.recipes.create.milling(['2x create:copper_nugget', Item.of('chain').withChance(0.25)], 'domesticationinnovation:collar_tag')
	event.recipes.create.milling(['2x gold_nugget', '2x quark:clear_shard', Item.of('rabbit_hide').withChance(0.25)], 'create:goggles')
	event.recipes.create.milling(['9x create:copper_nugget', '2x gold_nugget', Item.of('create:andesite_alloy').withChance(0.25)], 'create:potato_cannon')
	event.recipes.create.milling(['quark:soul_bead'], 'savage_and_ravage:wand_of_freezing')
	event.recipes.create.milling(['quark:soul_bead'], 'savage_and_ravage:conch_of_conjuring')
	event.recipes.create.milling(['quark:soul_bead'], 'savage_and_ravage:mask_of_dishonesty')
	event.recipes.create.milling([Item.of('oreganized:silver_nugget').withChance(0.3)], 'caverns_and_chasms:kunai')
	event.recipes.create.milling(['10x gold_nugget', '4x oreganized:silver_nugget'], 'oreganized:silver_mirror')
	event.recipes.create.milling(['6x iron_nugget'], 'bucket')
	event.recipes.create.milling(['stick'], 'bowl')
	event.recipes.create.milling(['quark:clear_shard'], 'glass_bottle')
	event.recipes.create.milling(['stick', Item.of('iron_nugget').withChance(0.1)], 'brewinandchewin:tankard')
	event.recipes.create.milling(['2x blue_dye', '2x green_dye', '8x gold_nugget'], 'supplementaries:globe')
	event.recipes.create.milling(['4x brown_dye', '8x gold_nugget'], 'supplementaries:globe_sepia')
})