// priority: 0

ServerEvents.recipes(event => {
	event.remove({ input: '#raspberry_flavoured:stone', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:stone_slab', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:stone', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:stone_slab', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:deepslate', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:deepslate_slab', type: 'minecraft:stonecutting' })
	event.remove({ input: '#create:stone_types/deepslate', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:deepslate', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:deepslate_slab', type: 'minecraft:stonecutting' })
	event.remove({ output: '#create:stone_types/deepslate', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:granite', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:granite_slab', type: 'minecraft:stonecutting' })
	event.remove({ input: '#create:stone_types/granite', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:granite', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:granite_slab', type: 'minecraft:stonecutting' })
	event.remove({ output: '#create:stone_types/granite', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:diorite', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:diorite_slab', type: 'minecraft:stonecutting' })
	event.remove({ input: '#create:stone_types/diorite', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:diorite', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:diorite_slab', type: 'minecraft:stonecutting' })
	event.remove({ output: '#create:stone_types/diorite', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:andesite', type: 'minecraft:stonecutting' })
	event.remove({ input: '#raspberry_flavoured:andesite_slab', type: 'minecraft:stonecutting' })
	event.remove({ input: '#create:stone_types/andesite', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:andesite', type: 'minecraft:stonecutting' })
	event.remove({ output: '#raspberry_flavoured:andesite_slab', type: 'minecraft:stonecutting' })
	event.remove({ output: '#create:stone_types/andesite', type: 'minecraft:stonecutting' })
	
	event.stonecutting('1x minecraft:stone', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:cobblestone', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:smooth_stone', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:cobblestone_stairs', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:stone_bricks', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:cracked_stone_bricks', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:chiseled_stone_bricks', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:stone_brick_stairs', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:stone_stairs', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:cobblestone_wall', '#raspberry_flavoured:stone')
	event.stonecutting('1x minecraft:stone_brick_wall', '#raspberry_flavoured:stone')
	event.stonecutting('1x supplementaries:stone_tile', '#raspberry_flavoured:stone')
	event.stonecutting('1x supplementaries:stone_tile_stairs', '#raspberry_flavoured:stone')
	event.stonecutting('1x supplementaries:stone_tile_wall', '#raspberry_flavoured:stone')
	event.stonecutting('1x paletteblocks:cobblestone_bricks', '#raspberry_flavoured:stone')
	event.stonecutting('1x paletteblocks:cracked_cobblestone_bricks', '#raspberry_flavoured:stone')
	event.stonecutting('1x paletteblocks:cobblestone_brick_stairs', '#raspberry_flavoured:stone')
	event.stonecutting('1x paletteblocks:cobblestone_brick_wall', '#raspberry_flavoured:stone')
	event.stonecutting('1x architects_palette:heavy_stone_bricks', '#raspberry_flavoured:stone')
	event.stonecutting('1x architects_palette:heavy_cracked_stone_bricks', '#raspberry_flavoured:stone')
	event.stonecutting('2x minecraft:stone_slab', '#raspberry_flavoured:stone')
	event.stonecutting('2x minecraft:smooth_stone_slab', '#raspberry_flavoured:stone')
	event.stonecutting('2x minecraft:cobblestone_slab', '#raspberry_flavoured:stone')
	event.stonecutting('2x minecraft:stone_brick_slab', '#raspberry_flavoured:stone')
	event.stonecutting('2x supplementaries:stone_tile_slab', '#raspberry_flavoured:stone')
	event.stonecutting('2x paletteblocks:cobblestone_brick_slab', '#raspberry_flavoured:stone')	
	event.stonecutting('1x minecraft:stone_slab', '#raspberry_flavoured:stone_slab')
	event.stonecutting('1x minecraft:smooth_stone_slab', '#raspberry_flavoured:stone_slab')
	event.stonecutting('1x minecraft:cobblestone_slab', '#raspberry_flavoured:stone_slab')
	event.stonecutting('1x minecraft:stone_brick_slab', '#raspberry_flavoured:stone_slab')
	event.stonecutting('1x supplementaries:stone_tile_slab', '#raspberry_flavoured:stone_slab')
	event.stonecutting('1x paletteblocks:cobblestone_brick_slab', '#raspberry_flavoured:stone_slab')
	
	event.stonecutting('1x minecraft:deepslate', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:cobbled_deepslate', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:polished_deepslate', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:deepslate_bricks', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:cracked_deepslate_bricks', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:deepslate_tiles', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:cracked_deepslate_tiles', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:chiseled_deepslate', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:cobbled_deepslate_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:polished_deepslate_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:deepslate_brick_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:deepslate_tile_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:cobbled_deepslate_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:polished_deepslate_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:deepslate_brick_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:deepslate_tile_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:cut_deepslate', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:cut_deepslate_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:cut_deepslate_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:polished_cut_deepslate', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:polished_cut_deepslate_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:polished_cut_deepslate_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:cut_deepslate_bricks', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:cut_deepslate_brick_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:cut_deepslate_brick_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:small_deepslate_bricks', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:small_deepslate_brick_stairs', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:small_deepslate_brick_wall', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:layered_deepslate', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x create:deepslate_pillar', '#raspberry_flavoured:deepslate')
	event.stonecutting('1x minecraft:cobbled_deepslate_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('1x minecraft:polished_deepslate_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('1x minecraft:deepslate_brick_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('1x minecraft:deepslate_tile_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('1x create:cut_deepslate_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('1x create:polished_cut_deepslate_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('1x create:cut_deepslate_brick_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('1x create:small_deepslate_brick_slab', '#raspberry_flavoured:deepslate_slab')
	event.stonecutting('2x minecraft:cobbled_deepslate_slab', '#raspberry_flavoured:deepslate')
	event.stonecutting('2x minecraft:polished_deepslate_slab', '#raspberry_flavoured:deepslate')
	event.stonecutting('2x minecraft:deepslate_brick_slab', '#raspberry_flavoured:deepslate')
	event.stonecutting('2x minecraft:deepslate_tile_slab', '#raspberry_flavoured:deepslate')
	event.stonecutting('2x create:cut_deepslate_slab', '#raspberry_flavoured:deepslate')
	event.stonecutting('2x create:polished_cut_deepslate_slab', '#raspberry_flavoured:deepslate')
	event.stonecutting('2x create:cut_deepslate_brick_slab', '#raspberry_flavoured:deepslate')
	event.stonecutting('2x create:small_deepslate_brick_slab', '#raspberry_flavoured:deepslate')

	event.stonecutting('1x minecraft:granite', '#raspberry_flavoured:granite')
	event.stonecutting('1x minecraft:polished_granite', '#raspberry_flavoured:granite')
	event.stonecutting('1x minecraft:granite_stairs', '#raspberry_flavoured:granite')
	event.stonecutting('1x minecraft:polished_granite_stairs', '#raspberry_flavoured:granite')
	event.stonecutting('1x minecraft:granite_wall', '#raspberry_flavoured:granite')
	event.stonecutting('1x quark:granite_bricks', '#raspberry_flavoured:granite')
	event.stonecutting('1x quark:granite_bricks_stairs', '#raspberry_flavoured:granite')
	event.stonecutting('1x quark:chiseled_granite_bricks', '#raspberry_flavoured:granite')
	event.stonecutting('1x quark:granite_pillar', '#raspberry_flavoured:granite')
	event.stonecutting('1x quark:granite_bricks_wall', '#raspberry_flavoured:granite')
	event.stonecutting('1x paletteblocks:polished_granite_wall', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:cut_granite', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:cut_granite_stairs', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:cut_granite_wall', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:polished_cut_granite', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:polished_cut_granite_stairs', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:polished_cut_granite_wall', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:cut_granite_bricks', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:cut_granite_brick_stairs', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:cut_granite_brick_wall', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:small_granite_bricks', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:small_granite_brick_stairs', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:small_granite_brick_wall', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:layered_granite', '#raspberry_flavoured:granite')
	event.stonecutting('1x create:granite_pillar', '#raspberry_flavoured:granite')
	event.stonecutting('2x minecraft:polished_granite_slab', '#raspberry_flavoured:granite')
	event.stonecutting('2x minecraft:granite_slab', '#raspberry_flavoured:granite')
	event.stonecutting('2x quark:granite_bricks_slab', '#raspberry_flavoured:granite')
	event.stonecutting('2x create:cut_granite_slab', '#raspberry_flavoured:granite')
	event.stonecutting('2x create:polished_cut_granite_slab', '#raspberry_flavoured:granite')
	event.stonecutting('2x create:cut_granite_brick_slab', '#raspberry_flavoured:granite')
	event.stonecutting('2x create:small_granite_brick_slab', '#raspberry_flavoured:granite')
	event.stonecutting('1x minecraft:polished_granite_slab', '#raspberry_flavoured:granite_slab')
	event.stonecutting('1x minecraft:granite_slab', '#raspberry_flavoured:granite_slab')
	event.stonecutting('1x quark:granite_bricks_slab', '#raspberry_flavoured:granite_slab')
	event.stonecutting('1x create:cut_granite_slab', '#raspberry_flavoured:granite_slab')
	event.stonecutting('1x create:polished_cut_granite_slab', '#raspberry_flavoured:granite_slab')
	event.stonecutting('1x create:cut_granite_brick_slab', '#raspberry_flavoured:granite_slab')
	event.stonecutting('1x create:small_granite_brick_slab', '#raspberry_flavoured:granite_slab')

	event.stonecutting('1x minecraft:diorite', '#raspberry_flavoured:diorite')
	event.stonecutting('1x minecraft:polished_diorite', '#raspberry_flavoured:diorite')
	event.stonecutting('1x minecraft:diorite_stairs', '#raspberry_flavoured:diorite')
	event.stonecutting('1x minecraft:polished_diorite_stairs', '#raspberry_flavoured:diorite')
	event.stonecutting('1x minecraft:diorite_wall', '#raspberry_flavoured:diorite')
	event.stonecutting('1x quark:diorite_bricks', '#raspberry_flavoured:diorite')
	event.stonecutting('1x quark:diorite_bricks_stairs', '#raspberry_flavoured:diorite')
	event.stonecutting('1x quark:chiseled_diorite_bricks', '#raspberry_flavoured:diorite')
	event.stonecutting('1x quark:diorite_pillar', '#raspberry_flavoured:diorite')
	event.stonecutting('1x quark:diorite_bricks_wall', '#raspberry_flavoured:diorite')
	event.stonecutting('1x paletteblocks:polished_diorite_wall', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:cut_diorite', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:cut_diorite_stairs', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:cut_diorite_wall', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:polished_cut_diorite', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:polished_cut_diorite_stairs', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:polished_cut_diorite_wall', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:cut_diorite_bricks', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:cut_diorite_brick_stairs', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:cut_diorite_brick_wall', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:small_diorite_bricks', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:small_diorite_brick_stairs', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:small_diorite_brick_wall', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:layered_diorite', '#raspberry_flavoured:diorite')
	event.stonecutting('1x create:diorite_pillar', '#raspberry_flavoured:diorite')
	event.stonecutting('2x minecraft:polished_diorite_slab', '#raspberry_flavoured:diorite')
	event.stonecutting('2x minecraft:diorite_slab', '#raspberry_flavoured:diorite')
	event.stonecutting('2x quark:diorite_bricks_slab', '#raspberry_flavoured:diorite')
	event.stonecutting('2x create:cut_diorite_slab', '#raspberry_flavoured:diorite')
	event.stonecutting('2x create:polished_cut_diorite_slab', '#raspberry_flavoured:diorite')
	event.stonecutting('2x create:cut_diorite_brick_slab', '#raspberry_flavoured:diorite')
	event.stonecutting('2x create:small_diorite_brick_slab', '#raspberry_flavoured:diorite')
	event.stonecutting('1x minecraft:polished_diorite_slab', '#raspberry_flavoured:diorite_slab')
	event.stonecutting('1x minecraft:diorite_slab', '#raspberry_flavoured:diorite_slab')
	event.stonecutting('1x quark:diorite_bricks_slab', '#raspberry_flavoured:diorite_slab')
	event.stonecutting('1x create:cut_diorite_slab', '#raspberry_flavoured:diorite_slab')
	event.stonecutting('1x create:polished_cut_diorite_slab', '#raspberry_flavoured:diorite_slab')
	event.stonecutting('1x create:cut_diorite_brick_slab', '#raspberry_flavoured:diorite_slab')
	event.stonecutting('1x create:small_diorite_brick_slab', '#raspberry_flavoured:diorite_slab')

	event.stonecutting('1x minecraft:andesite', '#raspberry_flavoured:andesite')
	event.stonecutting('1x minecraft:polished_andesite', '#raspberry_flavoured:andesite')
	event.stonecutting('1x minecraft:andesite_stairs', '#raspberry_flavoured:andesite')
	event.stonecutting('1x minecraft:polished_andesite_stairs', '#raspberry_flavoured:andesite')
	event.stonecutting('1x minecraft:andesite_wall', '#raspberry_flavoured:andesite')
	event.stonecutting('1x quark:andesite_bricks', '#raspberry_flavoured:andesite')
	event.stonecutting('1x quark:andesite_bricks_stairs', '#raspberry_flavoured:andesite')
	event.stonecutting('1x quark:chiseled_andesite_bricks', '#raspberry_flavoured:andesite')
	event.stonecutting('1x quark:andesite_pillar', '#raspberry_flavoured:andesite')
	event.stonecutting('1x quark:andesite_bricks_wall', '#raspberry_flavoured:andesite')
	event.stonecutting('1x paletteblocks:polished_andesite_wall', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:cut_andesite', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:cut_andesite_stairs', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:cut_andesite_wall', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:polished_cut_andesite', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:polished_cut_andesite_stairs', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:polished_cut_andesite_wall', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:cut_andesite_bricks', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:cut_andesite_brick_stairs', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:cut_andesite_brick_wall', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:small_andesite_bricks', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:small_andesite_brick_stairs', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:small_andesite_brick_wall', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:layered_andesite', '#raspberry_flavoured:andesite')
	event.stonecutting('1x create:andesite_pillar', '#raspberry_flavoured:andesite')
	event.stonecutting('2x minecraft:polished_andesite_slab', '#raspberry_flavoured:andesite')
	event.stonecutting('2x minecraft:andesite_slab', '#raspberry_flavoured:andesite')
	event.stonecutting('2x quark:andesite_bricks_slab', '#raspberry_flavoured:andesite')
	event.stonecutting('2x create:cut_andesite_slab', '#raspberry_flavoured:andesite')
	event.stonecutting('2x create:polished_cut_andesite_slab', '#raspberry_flavoured:andesite')
	event.stonecutting('2x create:cut_andesite_brick_slab', '#raspberry_flavoured:andesite')
	event.stonecutting('2x create:small_andesite_brick_slab', '#raspberry_flavoured:andesite')
	event.stonecutting('1x minecraft:polished_andesite_slab', '#raspberry_flavoured:andesite_slab')
	event.stonecutting('1x minecraft:andesite_slab', '#raspberry_flavoured:andesite_slab')
	event.stonecutting('1x quark:andesite_bricks_slab', '#raspberry_flavoured:andesite_slab')
	event.stonecutting('1x create:cut_andesite_slab', '#raspberry_flavoured:andesite_slab')
	event.stonecutting('1x create:polished_cut_andesite_slab', '#raspberry_flavoured:andesite_slab')
	event.stonecutting('1x create:cut_andesite_brick_slab', '#raspberry_flavoured:andesite_slab')
	event.stonecutting('1x create:small_andesite_brick_slab', '#raspberry_flavoured:andesite_slab')
})