#KubeJS Client Properties
#Wed Aug 19 23:09:20 EDT 2026
backgroundColor=2E3440
menuBackgroundBrightness=64
exportAtlases=false
barBorderColor=ECEFF4
disableRecipeBook=false
barColor=ECEFF4
title=Raspberry Flavoured 3.3
overrideColors=false
fmlLogColor=ECEFF4
showTagNames=false
fmlMemoryColor=ECEFF4
menuBackgroundScale=32.0
blurScaledPackIcon=true
menuInnerBackgroundBrightness=32
