models.2=2
biomes.2= jungle sparse_jungle bamboo_jungle atmospheric:rainforest atmospheric:sparse_rainforest atmospheric:rainforest_basin atmospheric:sparse_rainforest_basin
nbt.2.Owner=exists:false

models.3=3
name.3=Ocelot

models.4=4
name.4=Peachy Meachy Peachkin Meachkin Peachboy Meachboy Peacher Meacher

models.5=5
name.5=Sparky Sperky Spark Sperk Sparklepea Sperklepea Sparkboy Sperkboy

models.6=6
name.6=Molly

models.7=7
name.7=Sooty

models.666=666
name.666=Friend Image_Friend FRIEND IMAGE_FRIEND