// priority: 0
// script by QinomeD

const keysToItems = {
    'rf.jei.wooden_tools': ['minecraft:wooden_pickaxe','minecraft:wooden_shovel','minecraft:wooden_hoe','minecraft:wooden_axe','minecraft:wooden_sword'],
    'rf.jei.copper_tools': ['minecraft:stone_pickaxe', 'minecraft:stone_shovel', 'minecraft:stone_hoe', 'minecraft:stone_axe', 'minecraft:stone_sword', 'kubejs:copper_knife', 'minecraft:shears', 'another_furniture:furniture_hammer', 'supplementaries:wrench'],
    'rf.jei.iron_tools': ['minecraft:iron_pickaxe','minecraft:iron_shovel','minecraft:iron_hoe','minecraft:iron_axe','minecraft:iron_sword','farmersdelight:iron_knife'],
    'rf.jei.diamond_tools': ['minecraft:diamond_pickaxe','minecraft:diamond_shovel','minecraft:diamond_hoe','minecraft:diamond_axe','minecraft:diamond_sword','farmersdelight:diamond_knife','alloyed:steel_shears'],
    'rf.jei.golden_tools': ['minecraft:golden_pickaxe','minecraft:golden_shovel','minecraft:golden_hoe','minecraft:golden_axe','minecraft:golden_sword','farmersdelight:golden_knife'],
    'rf.jei.rose_gold_tools': ['additionaladditions:rose_gold_shovel', 'additionaladditions:rose_gold_pickaxe', 'additionaladditions:rose_gold_axe', 'additionaladditions:rose_gold_hoe', 'additionaladditions:rose_gold_sword', 'kubejs:rose_gold_knife'],
    'rf.jei.steel_tools': ['alloyed:steel_pickaxe', 'alloyed:steel_shovel', 'alloyed:steel_hoe', 'alloyed:steel_axe', 'alloyed:steel_sword', 'alloyed:steel_knife'],
    'rf.jei.electrum_tools': ['oreganized:electrum_pickaxe', 'oreganized:electrum_shovel', 'oreganized:electrum_hoe', 'oreganized:electrum_axe', 'oreganized:electrum_sword', 'oreganized:electrum_knife'],
    'rf.jei.necromium_tools': ['caverns_and_chasms:necromium_pickaxe', 'caverns_and_chasms:necromium_shovel', 'caverns_and_chasms:necromium_hoe', 'caverns_and_chasms:necromium_axe', 'caverns_and_chasms:necromium_sword', 'abnormals_delight:necromium_knife'],
    'rf.jei.netherite_tools': ['minecraft:netherite_pickaxe', 'minecraft:netherite_shovel', 'minecraft:netherite_hoe', 'minecraft:netherite_axe', 'minecraft:netherite_sword', 'farmersdelight:netherite_knife'],
    'rf.jei.leather_armor': ['minecraft:leather_helmet', 'minecraft:leather_chestplate', 'minecraft:leather_leggings', 'minecraft:leather_boots'],
    'rf.jei.copper_armor': ['copperized:copper_helmet', 'copperized:copper_chestplate', 'copperized:copper_leggings', 'copperized:copper_boots'],
    'rf.jei.chainmail_armor': ['minecraft:chainmail_helmet', 'minecraft:chainmail_chestplate', 'minecraft:chainmail_leggings', 'minecraft:chainmail_boots'],
    'rf.jei.iron_armor': ['minecraft:iron_helmet', 'minecraft:iron_chestplate', 'minecraft:iron_leggings', 'minecraft:iron_boots'],
    'rf.jei.diamond_armor': ['minecraft:diamond_helmet', 'minecraft:diamond_chestplate', 'minecraft:diamond_leggings', 'minecraft:diamond_boots'],
    'rf.jei.golden_armor': ['minecraft:golden_helmet', 'minecraft:golden_chestplate', 'minecraft:golden_leggings', 'minecraft:golden_boots'],
    'rf.jei.steel_armor': ['alloyed:steel_helmet', 'alloyed:steel_chestplate', 'alloyed:steel_leggings', 'alloyed:steel_boots'],
    'rf.jei.rose_gold_armor': ['additionaladditions:rose_gold_helmet', 'additionaladditions:rose_gold_chestplate', 'additionaladditions:rose_gold_leggings', 'additionaladditions:rose_gold_boots'],
    'rf.jei.electrum_armor': ['oreganized:electrum_helmet', 'oreganized:electrum_chestplate', 'oreganized:electrum_leggings', 'oreganized:electrum_boots'],
    'rf.jei.necromium_armor': ['caverns_and_chasms:necromium_helmet', 'caverns_and_chasms:necromium_chestplate', 'caverns_and_chasms:necromium_leggings', 'caverns_and_chasms:necromium_boots'],
    'rf.jei.netherite_armor': ['minecraft:netherite_helmet', 'minecraft:netherite_chestplate', 'minecraft:netherite_leggings', 'minecraft:netherite_boots'],
	
    'rf.jei.steel_mace': 'mace_backport:mace',
    'rf.jei.rose_gold_rapier': 'kubejs:rose_gold_rapier',
    'rf.jei.electrum_spear': 'clash:spear',
    'rf.jei.necromium_claymore': 'clash:greatblade',
    'rf.jei.netherite_broad_axe': 'clash:swept_axe',
	
    'rf.jei.hoes': '#forge:tools/hoes',
    'rf.jei.shears': '#forge:shears',
    'rf.jei.crab_claw': 'ecologics:crab_claw',
    'rf.jei.catching_net': 'naturalist:bug_net',
    'rf.jei.turtle_helmet': 'minecraft:turtle_helmet',
	
    'rf.jei.arrow': 'minecraft:arrow',
    'rf.jei.radiant_arrow': 'minecraft:spectral_arrow',
    'rf.jei.rose_gold_arrow': 'caverns_and_chasms:blunt_arrow',
    'rf.jei.steel_arrow': 'caverns_and_chasms:large_arrow',
    'rf.jei.torch_arrow': 'quark:torch_arrow',
    'rf.jei.rope_arrow': 'supplementaries:rope_arrow',
    'rf.jei.bananarrow': 'neapolitan:bananarrow',
    'rf.jei.mischief_arrow': 'savage_and_ravage:mischief_arrow',
    'rf.jei.lachryte_arrow': 'raspberry:swap_arrow',
	
    'rf.jei.bomb': 'supplementaries:bomb',
    'rf.jei.blue_bomb': 'supplementaries:bomb_blue',
    'rf.jei.spiky_bomb': 'supplementaries:bomb_spiky',
    'rf.jei.rose_gold_bomb': 'raspberry:rose_gold_bomb',
	
    'rf.jei.tea': ['#farmersrespite:tea_leaves', 'farmersrespite:wild_tea_bush', 'farmersrespite:tea_seeds'],
    'rf.jei.coffee': ['farmersrespite:coffee_beans', 'farmersrespite:coffee_berries', 'farmersrespite:wild_coffee_bush'],
    'rf.jei.wheat': ['minecraft:wheat_seeds', 'minecraft:wheat', 'minecraft:hay_block'],
    'rf.jei.pumpkin': ['minecraft:pumpkin_seeds', 'minecraft:pumpkin', 'minecraft:carved_pumpkin', 'farmersdelight:pumpkin_slice', 'autumnity:large_pumpkin_slice', 'autumnity:carved_large_pumpkin_slice'],
    'rf.jei.melons': ['minecraft:melon_seeds', 'minecraft:melon', 'minecraft:melon_slice'],
    'rf.jei.sweet_berries': ['minecraft:sweet_berries', 'berry_good:sweet_berry_pips', 'quark:berry_sack'],
    'rf.jei.glow_berries': ['minecraft:glow_berries', 'berry_good:glow_berry_pips', 'quark:glowberry_sack'],
    'rf.jei.foul_berries': ['autumnity:foul_berries', 'autumnity:foul_berry_pips', 'autumnity:foul_berry_basket'],
    'rf.jei.strawberries': ['neapolitan:strawberries', 'neapolitan:strawberry_basket', 'neapolitan:white_strawberries', 'neapolitan:white_strawberry_basket', 'neapolitan:strawberry_pips'],
    'rf.jei.mint': ['neapolitan:mint_leaves', 'neapolitan:mint_sprout', 'neapolitan:mint_basket'],
    'rf.jei.bananas': ['neapolitan:banana', 'neapolitan:banana_bunch', 'neapolitan:banana_bundle', 'neapolitan:banana_crate', 'neapolitan:banana_stalk', 'neapolitan:banana_frond'],
    'rf.jei.vanilla': ['neapolitan:vanilla_pods', 'neapolitan:dried_vanilla_pods', 'neapolitan:vanilla_pod_block', 'neapolitan:dried_vanilla_pod_block'],
    'rf.jei.flax': ['supplementaries:flax', 'supplementaries:flax_seeds', 'supplementaries:flax_block'],
    'rf.jei.eggplants': ['culturaldelights:eggplant_seeds', 'culturaldelights:eggplant', 'culturaldelights:eggplant_crate', 'culturaldelights:wild_eggplants'],
    'rf.jei.corn': ['culturaldelights:corn_kernels', 'culturaldelights:corn_cob', 'culturaldelights:corn_cob_crate', 'culturaldelights:wild_corn'],
    'rf.jei.avocados': ['#culturaldelights:avocados', 'culturaldelights:avocado_crate', 'culturaldelights:avocado_pit', 'culturaldelights:avocado_sapling', 'culturaldelights:fruiting_avocado_leaves'],
    'rf.jei.lemons': ['cookscollection:lemon', 'cookscollection:lemon_crate', 'cookscollection:lemon_sapling', 'cookscollection:fruiting_lemon_leaves'],
    'rf.jei.truffles': ['environmental:truffle', 'environmental:buried_truffle', 'environmental:truffle_crate'],
    'rf.jei.cattails': ['environmental:cattail', 'environmental:tall_cattail', 'environmental:cattail_seeds', 'environmental:cattail_seed_sack'],
	
    'rf.jei.coal': ['#minecraft:coal_ores', 'minecraft:coal', 'minecraft:coal_block', 'spelunkery:coal_lump'],
    'rf.jei.iron': ['#minecraft:iron_ores', 'minecraft:raw_iron', 'minecraft:raw_iron_block', 'minecraft:iron_ingot', 'minecraft:iron_block', 'spelunkery:raw_iron_nugget', 'minecraft:iron_nugget'],
    'rf.jei.copper': ['#minecraft:copper_ores', 'minecraft:raw_copper', 'minecraft:raw_copper_block', 'minecraft:copper_ingot', 'copperandtuffbackport:chiseled_copper', 'copperandtuffbackport:waxed_chiseled_copper', 'spelunkery:raw_copper_nugget', 'create:copper_nugget'],
    'rf.jei.gold': ['#minecraft:gold_ores', 'minecraft:gilded_blackstone', 'minecraft:raw_gold', 'minecraft:raw_gold_block', 'minecraft:gold_ingot', 'minecraft:gold_block', 'spelunkery:raw_gold_nugget', 'minecraft:gold_nugget'],
    'rf.jei.cinnabar': ['#minecraft:redstone_ores', 'spelunkery:rough_cinnabar', 'spelunkery:cinnabar', 'spelunkery:rough_cinnabar_block', 'spelunkery:cinnabar_block', 'spelunkery:rough_cinnabar_shard', 'spelunkery:cinnabar_shard'],
    'rf.jei.redstone': ['minecraft:redstone', 'minecraft:redstone_block'],
    'rf.jei.diamonds': ['#minecraft:diamond_ores', 'spelunkery:rough_diamond', 'spelunkery:rough_diamond_block', 'minecraft:diamond', 'minecraft:diamond_block', 'spelunkery:rough_diamond_shard', 'spelunkery:diamond_shard'],
    'rf.jei.ancient_debris': ['minecraft:ancient_debris', 'minecraft:netherite_scrap', 'kubejs:ancient_nugget'],
    'rf.jei.zinc': ['#forge:ores/zinc', 'create:raw_zinc', 'create:raw_zinc_block', 'create:zinc_ingot', 'create:zinc_block', 'spelunkery:raw_zinc_nugget', 'create:zinc_nugget'],
    'rf.jei.lead': ['#forge:ores/lead', 'oreganized:raw_lead', 'oreganized:raw_lead_block', 'oreganized:lead_ingot', 'oreganized:lead_block', 'spelunkery:raw_lead_nugget', 'oreganized:lead_nugget'],
    'rf.jei.silver': ['#forge:ores/silver', 'oreganized:raw_silver', 'oreganized:raw_silver_block', 'oreganized:silver_ingot', 'oreganized:silver_block', 'spelunkery:raw_silver_nugget', 'oreganized:silver_nugget', 'oreganized:silver_mirror'],
    'rf.jei.magnetite': ['spelunkery:magnetite', 'spelunkery:magnetite_chunk', 'spelunkery:raw_magnetite_nugget', 'spelunkery:magnetic_compass', 'minecraft:ancient_debris'],
    'rf.jei.quartz': ['minecraft:quartz', 'minecraft:nether_quartz_ore', 'spelunkery:rough_quartz_block', 'create:polished_rose_quartz', 'create:rose_quartz_tiles', 'kubejs:rough_quartz_shard', 'kubejs:quartz_shard'],
    'rf.jei.salt': ['spelunkery:salt', 'spelunkery:salt_block', 'spelunkery:rock_salt', 'spelunkery:rock_salt_block'],
    'rf.jei.blast_proof_ores': ['oreganized:silver_ore', '#forge:ores_in_ground/deepslate'],
	
    'rf.jei.campfires': '#raspberry_flavoured:campfires',
    'rf.jei.beds': '#minecraft:beds',
    'rf.jei.bedrolls': '#upgrade_aquatic:bedrolls',
    'rf.jei.composter': 'minecraft:composter',
    'rf.jei.organic_compost': 'farmersdelight:organic_compost',
    'rf.jei.rich_soil': ['farmersdelight:rich_soil', 'farmersdelight:rich_soil_farmland'],
    'rf.jei.feasts': '#raspberry_flavoured:feasts',
    'rf.jei.keg': 'brewinandchewin:keg',
    'rf.jei.echo_chest': 'echochest:echo_chest',
    'rf.jei.bellows': 'supplementaries:bellows',
	
    'rf.jei.leather_scraps': 'minecraft:rabbit_hide',
    'rf.jei.hoglin_hide': 'nethersdelight:hoglin_hide',
    'rf.jei.polishing': ['#create:sandpaper', 'minecraft:grindstone', 'spelunkery:rough_cinnabar', 'spelunkery:rough_diamond', 'minecraft:quartz'],
    'rf.jei.item_magnet': 'spelunkery:item_magnet',
    'rf.jei.echo_fork': 'spelunkery:echo_fork',
    'rf.jei.trowel': 'quark:trowel',
    'rf.jei.echorang': 'quark:echorang',
    'rf.jei.heart_of_the_sea': 'minecraft:heart_of_the_sea',
    'rf.jei.elder_eye': 'upgrade_aquatic:elder_eye',
    'rf.jei.paragliders': 'vc_gliders:paraglider_wood',
    'rf.jei.onion_cry': ['#forge:crops/onion', '#onion_onion:onion_proof_helmets'],
    'rf.jei.cloth_scraps': ['kubejs:cloth_scrap', '#raspberry_flavoured:cloth_blocks'],
    'rf.jei.brush': 'kubejs:copper_brush',
    'rf.jei.wax_brush': 'kubejs:copper_brush_wax',
    'rf.jei.sap': ['autumnity:sap_bottle', 'create_central_kitchen:sap_bucket', 'autumnity:sappy_maple_log', 'autumnity:sappy_maple_wood'],
    'rf.jei.latex': ['kubejs:latex_bottle', 'kubejs:latex_bucket', 'kubejs:latex_jungle_log', 'kubejs:latex_jungle_wood', 'kubejs:latex_rosewood_log', 'kubejs:latex_rosewood'],
    'rf.jei.rubber': ['kubejs:rubber', 'kubejs:rubber_block', 'kubejs:rubber_tire'],
    'rf.jei.cutting_board_sheets': ['create:copper_sheet', 'create:golden_sheet'],
    'rf.jei.creeper_spores': 'savage_and_ravage:creeper_spores',
    'rf.jei.glow_goop': 'naturalist:glow_goop',
    'rf.jei.yak_bear_fur': ['naturalist:bear_fur', 'environmental:yak_hair'],
	
    'rf.jei.compass': 'minecraft:compass',
    'rf.jei.recovery_compass': 'minecraft:recovery_compass',
    'rf.jei.magnetic_compass': 'spelunkery:magnetic_compass',
    'rf.jei.clock': 'minecraft:clock',
    'rf.jei.barometer': 'caverns_and_chasms:barometer',
    'rf.jei.spyglass': 'minecraft:spyglass',
    'rf.jei.depth_gauge': 'caverns_and_chasms:depth_gauge',
    'rf.jei.atlas': 'map_atlases:atlas',
    'rf.jei.silver_mirror': 'oreganized:silver_mirror',

    'rf.jei.wayward_lantern': 'domesticationinnovation:wayward_lantern',
    'rf.jei.collar_tags': 'domesticationinnovation:collar_tag',
    'rf.jei.deed_of_ownership': 'domesticationinnovation:deed_of_ownership',
    'rf.jei.command_drum': 'domesticationinnovation:drum',
	
    'rf.jei.awoken_exopearl': 'minecraft:ender_eye',
    'rf.jei.spirited_exopearl': 'kubejs:spirited_exopearl',
    'rf.jei.binding_exopearl': 'heartstone:heartstone',
    'rf.jei.soul_bead': 'quark:soul_bead',
    'rf.jei.echo_shard': 'minecraft:echo_shard',
    'rf.jei.lachryte': 'minecraft:ghast_tear',
    'rf.jei.dimensional_tears_bottle': 'spelunkery:portal_fluid_bottle',
    'rf.jei.dimensional_tears_bucket': 'spelunkery:portal_fluid_bucket',

    'rf.jei.anvil': 'minecraft:anvil',
    'rf.jei.forge': 'modestmining:forge',
    'rf.jei.enchanted_tablets': '#raspberry_flavoured:all_enchanted_tablets',
    'rf.jei.runes': '#quark:runes',
    'rf.jei.stardust': 'kubejs:stardust',
	
    'rf.jei.tackle_box': ['aquaculture:tackle_box', 'aquaculture:iron_fishing_rod'],
    'rf.jei.hooks': '#raspberry_flavoured:hooks',
    'rf.jei.magnetite_hook': 'aquaculture:gold_hook',
    'rf.jei.copper_hook': 'aquaculture:light_hook',
    'rf.jei.steel_hook': 'aquaculture:heavy_hook',
    'rf.jei.double_hook': 'aquaculture:double_hook',
    'rf.jei.zinc_hook': 'aquaculture:redstone_hook',
	
    'rf.jei.worms': ['aquaculture:worm', 'raspberry:wormy_dirt'],
    'rf.jei.spider_eye': 'minecraft:spider_eye',
    'rf.jei.firefly': 'raspberry:firefly',
    'rf.jei.caterpillar': 'naturalist:caterpillar',
    'rf.jei.golden_worm': 'kubejs:golden_worm',
	
    'rf.jei.dwarf_geode': 'kubejs:dwarf_geode',
    'rf.jei.deepslate_dwarf_geode': 'kubejs:deepslate_dwarf_geode',
    'rf.jei.blackstone_dwarf_geode': 'kubejs:blackstone_dwarf_geode',
	
    'rf.jei.loot_bags': '#raspberry_flavoured:loot_bags',
	
    'rf.jei.totem_of_undying': 'minecraft:totem_of_undying',
    'rf.jei.wand_of_freezing': 'savage_and_ravage:wand_of_freezing',
    'rf.jei.mask_of_dishonesty': 'savage_and_ravage:mask_of_dishonesty',
    'rf.jei.conch_of_conjuring': 'savage_and_ravage:conch_of_conjuring',
	
    'rf.jei.stone_and_deepslate': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:cobblestone', 'minecraft:stone', 'minecraft:cobbled_deepslate', 'minecraft:deepslate'],
    'rf.jei.blackstone': ['minecraft:blue_ice', 'minecraft:lava_bucket', 'minecraft:netherrack', 'kubejs:cobbled_blackstone', 'minecraft:blackstone'],
    'rf.jei.basalt': ['minecraft:blue_ice', 'minecraft:lava_bucket', 'minecraft:soul_soil', 'minecraft:smooth_basalt'],
    'rf.jei.granite': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:red_sand', 'minecraft:granite'],
    'rf.jei.diorite': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:calcite', 'minecraft:diorite'],
    'rf.jei.andesite': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:gravel', 'minecraft:andesite'],
    'rf.jei.dripstone': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:packed_mud', 'minecraft:dripstone_block'],
    'rf.jei.calcite': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:bone_block', 'minecraft:calcite'],
    'rf.jei.tuff': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'raspberry:deepslate_gravel', 'minecraft:tuff'],
    'rf.jei.crimsite': ['kubejs:scarlet_cheese_bucket', 'minecraft:lava_bucket', 'create:crimsite'],
    'rf.jei.ochrum': ['create:honey_bucket', 'minecraft:lava_bucket', 'create:ochrum'],
    'rf.jei.asurine': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:emerald_block', 'create:asurine'],
    'rf.jei.veridium': ['minecraft:water_bucket', 'minecraft:lava_bucket', 'additionaladditions:patina_block', 'create:veridium'],
    'rf.jei.limestone': ['kubejs:batter_bucket', 'minecraft:lava_bucket', 'create:limestone'],
    'rf.jei.scoria': ['create:chocolate_bucket', 'minecraft:lava_bucket', 'create:scoria'],
    'rf.jei.glance': ['oreganized:molten_lead_bucket', 'minecraft:lava_bucket', 'oreganized:glance'],
    'rf.jei.exolite': ['minecraft:blue_ice', 'minecraft:lava_bucket', 'architects_palette:ender_pearl_block', 'kubejs:cobbled_exolite', 'kubejs:exolite', 'endergetic:poismoss'],
	
    'rf.jei.etching': ['etched:etching_table', 'etched:blank_music_disc', 'etched:music_label'],
    'rf.jei.album_cover': 'etched:album_cover',
    'rf.jei.radio': 'etched:radio',
    'rf.jei.boombox': 'etched:boombox',
	
    'rf.jei.creeper_discs': '#minecraft:creeper_drop_music_discs',
    'rf.jei.dungeon_discs': ['minecraft:music_disc_13', 'minecraft:music_disc_cat', 'minecraft:music_disc_wait'],
    'rf.jei.scour_disc': 'sullysmod:music_disc_scour',
    'rf.jei.ward_disc': 'minecraft:music_disc_ward',
    'rf.jei.mellohi_disc': 'minecraft:music_disc_mellohi',
    'rf.jei.far_strad_discs': ['minecraft:music_disc_far', 'minecraft:music_disc_strad'],
    'rf.jei.blocks_mall_discs': ['minecraft:music_disc_blocks', 'minecraft:music_disc_mall'],
    'rf.jei.stal_11_discs': ['minecraft:music_disc_stal', 'minecraft:music_disc_11'],
    'rf.jei.otherside_disc': 'minecraft:music_disc_otherside',
    'rf.jei.pigstep_disc': 'minecraft:music_disc_pigstep',
    'rf.jei.structure_disc': 'oreganized:music_disc_structure',
    'rf.jei.fox_disc': 'berry_good:music_disc_fox',
    'rf.jei.coconut_disc': 'ecologics:music_disc_coconut',
    'rf.jei.slabrave_disc': 'environmental:music_disc_slabrave',
    'rf.jei.hullabaloo_disc': 'neapolitan:music_disc_hullabaloo',
    'rf.jei.death_disc': 'kubejs:music_disc_death',
    'rf.jei.droopy1_disc': 'kubejs:music_disc_droopy1',
    'rf.jei.raveyard_disc': 'kubejs:music_disc_raveyard',
    'rf.jei.exostep': 'kubejs:music_disc_exostep',
    'rf.jei.precipice_disc': 'trickytrialspaintingsplusmusic:music_disc_precipice',
    'rf.jei.creator_disc': 'trickytrialspaintingsplusmusic:music_disc_creator',
    'rf.jei.relic_disc': 'trickytrialspaintingsplusmusic:music_disc_relic',
    'rf.jei.atlantis_disc': 'upgrade_aquatic:music_disc_atlantis',
	
    'farmersdelight.jei.info.knife': ['kubejs:bone_knife', 'kubejs:copper_knife', 'kubejs:rose_gold_knife', 'alloyed:steel_knife', 'oreganized:electrum_knife', 'abnormals_delight:necromium_knife'],
	
    'farmersdelight.jei.info.wild_cabbages': ['farmersdelight:cabbage_seeds', 'farmersdelight:cabbage_crate'],
    'farmersdelight.jei.info.wild_beetroots': ['minecraft:beetroot_seeds', 'farmersdelight:beetroot_crate'],
    'farmersdelight.jei.info.wild_carrots': ['farmersdelight:carrot_crate', 'kubejs:spoiled_carrot'],
    'farmersdelight.jei.info.wild_onions': ['onion_onion:onion_slice', 'farmersdelight:onion_crate'],
    'farmersdelight.jei.info.wild_potatoes': ['farmersdelight:potato_crate', 'minecraft:poisonous_potato'],
    'farmersdelight.jei.info.wild_tomatoes': ['farmersdelight:tomato_seeds', 'farmersdelight:tomato_crate'],
    'farmersdelight.jei.info.wild_rice': ['farmersdelight:rice_bag', 'farmersdelight:rice_bale'],
	
    'architects_palette.info.chiseled_chargeable': 'minecraft:heart_of_the_sea'
}

JEIEvents.information(event => {
	for (const [key, items] of Object.entries(keysToItems)) {
        event.addItem(items, Text.translate(key))
    }
})