// priority: 0

console.info('Hello, World! (You will see this line every time client resources reload)')

JEIEvents.hideItems(event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')
})

ItemEvents.tooltip(tooltip => {
  tooltip.add(['abnormals_delight:vanilla_cake_slice'], "§9Vanilla Scent (0:05)")
  tooltip.add(['abnormals_delight:chocolate_cake_slice'], "§9Sugar Rush (0:10)")
  tooltip.add(['abnormals_delight:banana_cake_slice'], "§9Agility (0:10)")
  tooltip.add(['abnormals_delight:mint_cake_slice'], "§9Berserking (0:15)")
  tooltip.add(['abnormals_delight:adzuki_cake_slice'], "§9Harmony (0:10)")
  tooltip.add(['abnormals_delight:yucca_gateau_slice'], "§9Persistence (0:15)")
  tooltip.add(['abnormals_delight:strawberry_cake_slice'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:strawberries'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:white_strawberries'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:strawberry_scones'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:strawberry_ice_cream'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:chocolate_strawberries'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:strawberry_banana_smoothie'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:chocolate_milkshake'], "§7When drunk or given to a mob:")
  tooltip.add(['neapolitan:chocolate_milkshake'], "§9 Clears Beneficial Effects")
  tooltip.add(['neapolitan:strawberry_milkshake'], "§7When drunk or given to a mob:")
  tooltip.add(['neapolitan:strawberry_milkshake'], "§9 Clears Harmful Effects")
  tooltip.add(['neapolitan:vanilla_milkshake'], "§7When drunk or given to a mob:")
  tooltip.add(['neapolitan:vanilla_milkshake'], "§9 Clears All Effects")
  tooltip.add(['neapolitan:banana_milkshake'], "§7When drunk:")
  tooltip.add(['neapolitan:banana_milkshake'], "§9 Swap Effects with Nearby Mob")
  tooltip.add(['neapolitan:mint_milkshake'], "§7When drunk:")
  tooltip.add(['neapolitan:mint_milkshake'], "§9 Take Effects from Nearby Mob")
  tooltip.add(['neapolitan:adzuki_milkshake'], "§7When drunk:")
  tooltip.add(['neapolitan:adzuki_milkshake'], "§9 Give Effects to Nearby Mob")
  tooltip.add(['neapolitan:neapolitan_ice_cream'], "§cSlowness III (0:05)")
  tooltip.add(['neapolitan:neapolitan_ice_cream'], "§9Minor Instant Health")
  tooltip.add(['neapolitan:neapolitan_ice_cream'], "§9Sugar Rush II (0:20)")
  tooltip.add(['neapolitan:neapolitan_ice_cream'], "§9Vanilla Scent (0:10)")
  tooltip.addAdvanced('bigbrain:buckler', (item, advanced, text) => {
    text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
	text.remove(1)
  })
})